import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_AlpakaBackendProducer import alpaka_cuda_async_AlpakaBackendProducer

alpaka_cuda_asyncAlpakaBackendProducer = alpaka_cuda_async_AlpakaBackendProducer()
