import FWCore.ParameterSet.Config as cms

from .AllBarrelTracksterToSimTracksterAssociatorsByHitsProducer import AllBarrelTracksterToSimTracksterAssociatorsByHitsProducer

AllBarrelTracksterToSimTracksterAssociatorsByHitsProducer = AllBarrelTracksterToSimTracksterAssociatorsByHitsProducer()
