import FWCore.ParameterSet.Config as cms

from .AllHitToBarrelTracksterAssociatorsProducer import AllHitToBarrelTracksterAssociatorsProducer

AllHitToBarrelTracksterAssociatorsProducer = AllHitToBarrelTracksterAssociatorsProducer()
