import FWCore.ParameterSet.Config as cms

from .AllHitToTracksterAssociatorsProducer import AllHitToTracksterAssociatorsProducer

AllHitToTracksterAssociatorsProducer = AllHitToTracksterAssociatorsProducer()
