import FWCore.ParameterSet.Config as cms

from .AllLayerClusterToTracksterAssociatorsProducer import AllLayerClusterToTracksterAssociatorsProducer

AllLayerClusterToTracksterAssociatorsProducer = AllLayerClusterToTracksterAssociatorsProducer()
