import FWCore.ParameterSet.Config as cms

from .AllTracksterToSimTracksterAssociatorsByLCsProducer import AllTracksterToSimTracksterAssociatorsByLCsProducer

AllTracksterToSimTracksterAssociatorsByLCsProducer = AllTracksterToSimTracksterAssociatorsByLCsProducer()
