import FWCore.ParameterSet.Config as cms

from .AllTracksterToSimTracksterAssociatorsByHitsProducer import AllTracksterToSimTracksterAssociatorsByHitsProducer

AllTracksterToSimTracksterAssociatorsByHitsProducer = AllTracksterToSimTracksterAssociatorsByHitsProducer()
