import FWCore.ParameterSet.Config as cms

from .BarrelPCToSCAssociatorByEnergyScoreProducer import BarrelPCToSCAssociatorByEnergyScoreProducer

barrelPCToSCAssociatorByEnergyScoreProducer = BarrelPCToSCAssociatorByEnergyScoreProducer()
