import FWCore.ParameterSet.Config as cms

from .BarrelLCToSCAssociatorByEnergyScoreProducer import BarrelLCToSCAssociatorByEnergyScoreProducer

barrelLCToSCAssociatorByEnergyScoreProducer = BarrelLCToSCAssociatorByEnergyScoreProducer()
