import FWCore.ParameterSet.Config as cms

from .BarrelHitToSimClusterCaloParticleAssociatorProducer import BarrelHitToSimClusterCaloParticleAssociatorProducer

barrelHitToSimClusterCaloParticleAssociator = BarrelHitToSimClusterCaloParticleAssociatorProducer()
