import FWCore.ParameterSet.Config as cms

from .BarrelPCToCPAssociatorByEnergyScoreProducer import BarrelPCToCPAssociatorByEnergyScoreProducer

barrelPCToCPAssociatorByEnergyScoreProducer = BarrelPCToCPAssociatorByEnergyScoreProducer()
