import FWCore.ParameterSet.Config as cms

from .BarrelLCToCPAssociatorByEnergyScoreProducer import BarrelLCToCPAssociatorByEnergyScoreProducer

barrelLCToCPAssociatorByEnergyScoreProducer = BarrelLCToCPAssociatorByEnergyScoreProducer()
