import FWCore.ParameterSet.Config as cms

from .BarrelTSToSimTSHitLCAssociatorByEnergyScoreProducer import BarrelTSToSimTSHitLCAssociatorByEnergyScoreProducer

barrelSimTracksterHitLCAssociatorByEnergyScore = BarrelTSToSimTSHitLCAssociatorByEnergyScoreProducer()
