import FWCore.ParameterSet.Config as cms

from .HGCalLCToSCAssociatorByEnergyScoreProducer import HGCalLCToSCAssociatorByEnergyScoreProducer

hgCalLCToSCAssociatorByEnergyScoreProducer = HGCalLCToSCAssociatorByEnergyScoreProducer()
