import FWCore.ParameterSet.Config as cms

from .HGCalTSToSimTSHitLCAssociatorByEnergyScoreProducer import HGCalTSToSimTSHitLCAssociatorByEnergyScoreProducer

hgcalSimTracksterHitLCAssociatorByEnergyScore = HGCalTSToSimTSHitLCAssociatorByEnergyScoreProducer()
