import FWCore.ParameterSet.Config as cms

from .HGCalLCToCPAssociatorByEnergyScoreProducer import HGCalLCToCPAssociatorByEnergyScoreProducer

hgCalLCToCPAssociatorByEnergyScoreProducer = HGCalLCToCPAssociatorByEnergyScoreProducer()
