import FWCore.ParameterSet.Config as cms

from .HGCalPCToCPAssociatorByEnergyScoreProducer import HGCalPCToCPAssociatorByEnergyScoreProducer

hgCalPCToCPAssociatorByEnergyScoreProducer = HGCalPCToCPAssociatorByEnergyScoreProducer()
