import FWCore.ParameterSet.Config as cms

from .HGCalPCToSCAssociatorByEnergyScoreProducer import HGCalPCToSCAssociatorByEnergyScoreProducer

hgCalPCToSCAssociatorByEnergyScoreProducer = HGCalPCToSCAssociatorByEnergyScoreProducer()
