import FWCore.ParameterSet.Config as cms

from .HitToBarrelTracksterAssociatorProducer import HitToBarrelTracksterAssociatorProducer

hitToBarrelTracksterAssociator = HitToBarrelTracksterAssociatorProducer()
