import FWCore.ParameterSet.Config as cms

from .HitToSimClusterCaloParticleAssociatorProducer import HitToSimClusterCaloParticleAssociatorProducer

hitToSimClusterCaloParticleAssociator = HitToSimClusterCaloParticleAssociatorProducer()
