import FWCore.ParameterSet.Config as cms

from .HitToBarrelLayerClusterAssociatorProducer import HitToBarrelLayerClusterAssociatorProducer

hitToBarrelLayerClusterAssociator = HitToBarrelLayerClusterAssociatorProducer()
