import FWCore.ParameterSet.Config as cms

from .LCToSimTSAssociatorByEnergyScoreProducer import LCToSimTSAssociatorByEnergyScoreProducer

layerClusterSimTracksterAssociatorByEnergyScore = LCToSimTSAssociatorByEnergyScoreProducer()
