import FWCore.ParameterSet.Config as cms

from .LCToCPAssociatorByEnergyScoreProducer import LCToCPAssociatorByEnergyScoreProducer

layerClusterAssociatorByEnergyScore = LCToCPAssociatorByEnergyScoreProducer()
