import FWCore.ParameterSet.Config as cms

from .MultiClusterAssociatorByEnergyScoreProducer import MultiClusterAssociatorByEnergyScoreProducer

multiClusterAssociatorByEnergyScore = MultiClusterAssociatorByEnergyScoreProducer()
