import FWCore.ParameterSet.Config as cms

from .SimClusterToCaloParticleAssociatorProducer import SimClusterToCaloParticleAssociatorProducer

SimClusterToCaloParticleAssociatorProducer = SimClusterToCaloParticleAssociatorProducer()
