import FWCore.ParameterSet.Config as cms

from .LCToSCAssociatorByEnergyScoreProducer import LCToSCAssociatorByEnergyScoreProducer

simClusterAssociatorByEnergyScore = LCToSCAssociatorByEnergyScoreProducer()
