import FWCore.ParameterSet.Config as cms

from .TSToSimTSAssociatorByEnergyScoreProducer import TSToSimTSAssociatorByEnergyScoreProducer

simTracksterAssociatorByEnergyScore = TSToSimTSAssociatorByEnergyScoreProducer()
