import FWCore.ParameterSet.Config as cms

from .TSToSimTSHitLCAssociatorByEnergyScoreProducer import TSToSimTSHitLCAssociatorByEnergyScoreProducer

simTracksterHitLCAssociatorByEnergyScore = TSToSimTSHitLCAssociatorByEnergyScoreProducer()
