import FWCore.ParameterSet.Config as cms

from .TracksterToSimTracksterAssociatorProducer import TracksterToSimTracksterAssociatorProducer

tracksterToSimTracksterAssociatorProducer = TracksterToSimTracksterAssociatorProducer()
