import FWCore.ParameterSet.Config as cms

from .TSToSCAssociatorByEnergyScoreProducer import TSToSCAssociatorByEnergyScoreProducer

tracksterAssociatorByEnergyScore = TSToSCAssociatorByEnergyScoreProducer()
