import FWCore.ParameterSet.Config as cms

from .TracksterToSimTracksterAssociatorByHitsProducer import TracksterToSimTracksterAssociatorByHitsProducer

tracksterToSimTracksterAssociatorByHitsProducer = TracksterToSimTracksterAssociatorByHitsProducer()
