import FWCore.ParameterSet.Config as cms

from .FastSiPixelFEDChannelContainerFromQuality import FastSiPixelFEDChannelContainerFromQuality

FastSiPixelFEDChannelContainerFromQuality = FastSiPixelFEDChannelContainerFromQuality()
