import FWCore.ParameterSet.Config as cms

from .SiPixelGainCalibrationRejectNoisyAndDead import SiPixelGainCalibrationRejectNoisyAndDead

siPixelGainCalibrationRejectNoisyAndDead = SiPixelGainCalibrationRejectNoisyAndDead()
