import FWCore.ParameterSet.Config as cms

from .SiPixelFEDChannelContainerTestReader import SiPixelFEDChannelContainerTestReader

SiPixelFEDChannelContainerTestReader = SiPixelFEDChannelContainerTestReader()
