import FWCore.ParameterSet.Config as cms

from .SiPixelQualityProbabilitiesTestWriter import SiPixelQualityProbabilitiesTestWriter

SiPixelQualityProbabilitiesTestWriter = SiPixelQualityProbabilitiesTestWriter()
