import FWCore.ParameterSet.Config as cms

from .SiPixelFEDChannelContainerFromQualityConverter import SiPixelFEDChannelContainerFromQualityConverter

SiPixelFEDChannelContainerFromQualityConverter = SiPixelFEDChannelContainerFromQualityConverter()
