import FWCore.ParameterSet.Config as cms

from .SiPixelBadFEDChannelSimulationSanityChecker import SiPixelBadFEDChannelSimulationSanityChecker

SiPixelBadFEDChannelSimulationSanityChecker = SiPixelBadFEDChannelSimulationSanityChecker()
