import FWCore.ParameterSet.Config as cms

from .SiPixelQualityProbabilitiesWriteFromASCII import SiPixelQualityProbabilitiesWriteFromASCII

SiPixelQualityProbabilitiesWriteFromASCII = SiPixelQualityProbabilitiesWriteFromASCII()
