import FWCore.ParameterSet.Config as cms

from .SiPixelQualityProbabilitiesTestReader import SiPixelQualityProbabilitiesTestReader

SiPixelQualityProbabilitiesTestReader = SiPixelQualityProbabilitiesTestReader()
