import FWCore.ParameterSet.Config as cms

from .SiPixelFEDChannelContainerWriteFromASCII import SiPixelFEDChannelContainerWriteFromASCII

SiPixelFEDChannelContainerWriteFromASCII = SiPixelFEDChannelContainerWriteFromASCII()
