import FWCore.ParameterSet.Config as cms

from .PPSDiamondSampicTimingCalibrationPCLHarvester import PPSDiamondSampicTimingCalibrationPCLHarvester

PPSDiamondSampicTimingCalibrationPCLHarvester = PPSDiamondSampicTimingCalibrationPCLHarvester()
