import FWCore.ParameterSet.Config as cms

from .PPSDiamondSampicTimingCalibrationPCLWorker import PPSDiamondSampicTimingCalibrationPCLWorker

PPSDiamondSampicTimingCalibrationPCLWorker = PPSDiamondSampicTimingCalibrationPCLWorker()
