import FWCore.ParameterSet.Config as cms

from .EgammaHLTFilteredEcalCandPtrProducer import EgammaHLTFilteredEcalCandPtrProducer

egammaHLTFilteredEcalCandPtrProducer = EgammaHLTFilteredEcalCandPtrProducer()
