import FWCore.ParameterSet.Config as cms

from .EgammaHLTFilteredSuperClusterProducer import EgammaHLTFilteredSuperClusterProducer

egammaHLTFilteredSuperClusterProducer = EgammaHLTFilteredSuperClusterProducer()
