import FWCore.ParameterSet.Config as cms

from .HLTEcalRecHitsInRegionsProducer import HLTEcalRecHitsInRegionsProducer

hltCaloObjInRegionsProducerEcalRecHitEdmSortedCollectionEcalRecHitEdmStrictWeakOrderingEcalRecHit = HLTEcalRecHitsInRegionsProducer()
