import FWCore.ParameterSet.Config as cms

from .HLTEcalESDigisInRegionsProducer import HLTEcalESDigisInRegionsProducer

hltCaloObjInRegionsProducerESDataFrameESDigiCollection = HLTEcalESDigisInRegionsProducer()
