import FWCore.ParameterSet.Config as cms

from .HLTHGCalRecHitsInRegionsProducer import HLTHGCalRecHitsInRegionsProducer

hltCaloObjInRegionsProducerHGCRecHitEdmSortedCollectionHGCRecHitEdmStrictWeakOrderingHGCRecHit = HLTHGCalRecHitsInRegionsProducer()
