import FWCore.ParameterSet.Config as cms

from .HLTHcalDigisInRegionsProducer import HLTHcalDigisInRegionsProducer

hltCaloObjInRegionsProducerHBHEDataFrameEdmSortedCollectionHBHEDataFrameEdmStrictWeakOrderingHBHEDataFrame = HLTHcalDigisInRegionsProducer()
