import FWCore.ParameterSet.Config as cms

from .HLTHGCalDigisInRegionsProducer import HLTHGCalDigisInRegionsProducer

hltCaloObjInRegionsProducerHGCDataFrameDetIdHGCSampleEdmSortedCollectionHGCDataFrameDetIdHGCSampleEdmStrictWeakOrderingHGCDataFrameDetIdHGCSample = HLTHGCalDigisInRegionsProducer()
