import FWCore.ParameterSet.Config as cms

from .HLTHGCalRecHitsInRegionsProducer import HLTHGCalRecHitsInRegionsProducer

hltCaloObjInRegionsProducerHGCRecHitStdVectorHGCRecHitStdAllocatorHGCRecHit = HLTHGCalRecHitsInRegionsProducer()
