import FWCore.ParameterSet.Config as cms

from .HLTHGCalUncalibratedRecHitsInRegionsProducer import HLTHGCalUncalibratedRecHitsInRegionsProducer

hltCaloObjInRegionsProducerHGCUncalibratedRecHitEdmSortedCollectionHGCUncalibratedRecHitEdmStrictWeakOrderingHGCUncalibratedRecHit = HLTHGCalUncalibratedRecHitsInRegionsProducer()
