import FWCore.ParameterSet.Config as cms

from .HLTEcalEEDigisInRegionsProducer import HLTEcalEEDigisInRegionsProducer

hltCaloObjInRegionsProducerEEDataFrameEEDigiCollection = HLTEcalEEDigisInRegionsProducer()
