import FWCore.ParameterSet.Config as cms

from .HLTEcalUnCalibRecHitsInRegionsProducer import HLTEcalUnCalibRecHitsInRegionsProducer

hltCaloObjInRegionsProducerEcalUncalibratedRecHitEdmSortedCollectionEcalUncalibratedRecHitEdmStrictWeakOrderingEcalUncalibratedRecHit = HLTEcalUnCalibRecHitsInRegionsProducer()
