import FWCore.ParameterSet.Config as cms

from .HLTEcalEBDigisInRegionsProducer import HLTEcalEBDigisInRegionsProducer

hltCaloObjInRegionsProducerEBDataFrameEBDigiCollection = HLTEcalEBDigisInRegionsProducer()
