import FWCore.ParameterSet.Config as cms

hltESListOfFEDSProducer = cms.EDProducer('ESListOfFEDSProducer',
  debug = cms.bool(False),
  EGamma = cms.bool(True),
  Muon = cms.bool(False),
  Jets = cms.bool(False),
  EM_l1TagIsolated = cms.InputTag('l1extraParticles', 'Isolated'),
  EM_l1TagNonIsolated = cms.InputTag('l1extraParticles', 'NonIsolated'),
  EM_doIsolated = cms.bool(True),
  EM_doNonIsolated = cms.bool(True),
  EM_regionEtaMargin = cms.double(0.25),
  EM_regionPhiMargin = cms.double(0.4),
  Ptmin_iso = cms.double(5),
  Ptmin_noniso = cms.double(5),
  MU_regionEtaMargin = cms.double(1),
  MU_regionPhiMargin = cms.double(1),
  Ptmin_muon = cms.double(0),
  MuonSource = cms.InputTag('l1extraParticles'),
  JETS_regionEtaMargin = cms.double(1),
  JETS_regionPhiMargin = cms.double(1),
  Ptmin_jets = cms.double(50),
  CentralSource = cms.InputTag('l1extraParticles', 'Central'),
  ForwardSource = cms.InputTag('l1extraParticles', 'Forward'),
  TauSource = cms.InputTag('l1extraParticles', 'Tau'),
  JETS_doCentral = cms.bool(True),
  JETS_doForward = cms.bool(True),
  JETS_doTau = cms.bool(True),
  OutputLabel = cms.string('')
)
