import FWCore.ParameterSet.Config as cms

from .EgammaHLTPhotonTrackIsolationProducersRegional import EgammaHLTPhotonTrackIsolationProducersRegional

hltEgammaHLTPhotonTrackIsolationProducersRegional = EgammaHLTPhotonTrackIsolationProducersRegional()
