import FWCore.ParameterSet.Config as cms

hltEcalListOfFEDSProducer = cms.EDProducer('EcalListOfFEDSProducer',
  debug = cms.bool(False),
  Pi0ListToIgnore = cms.InputTag(''),
  EGamma = cms.bool(False),
  Muon = cms.bool(False),
  Jets = cms.bool(False),
  EM_l1TagIsolated = cms.InputTag(''),
  EM_l1TagNonIsolated = cms.InputTag(''),
  EM_doIsolated = cms.bool(True),
  EM_doNonIsolated = cms.bool(True),
  EM_regionEtaMargin = cms.double(0.25),
  EM_regionPhiMargin = cms.double(0.4),
  Ptmin_iso = cms.double(0),
  Ptmin_noniso = cms.double(0),
  MU_regionEtaMargin = cms.double(1),
  MU_regionPhiMargin = cms.double(1),
  Ptmin_muon = cms.double(0),
  MuonSource = cms.InputTag(''),
  JETS_regionEtaMargin = cms.double(1),
  JETS_regionPhiMargin = cms.double(1),
  Ptmin_jets = cms.double(0),
  CentralSource = cms.InputTag(''),
  ForwardSource = cms.InputTag(''),
  TauSource = cms.InputTag(''),
  JETS_doCentral = cms.bool(True),
  JETS_doForward = cms.bool(True),
  JETS_doTau = cms.bool(True),
  OutputLabel = cms.string('')
)
