import FWCore.ParameterSet.Config as cms

from .EgammaHLTEcalPFClusterIsolationProducer import EgammaHLTEcalPFClusterIsolationProducer

hltEcalPFClusterIsolationProducerRecoRecoEcalCandidate = EgammaHLTEcalPFClusterIsolationProducer()
