import FWCore.ParameterSet.Config as cms

from .MuonHLTEcalPFClusterIsolationProducer import MuonHLTEcalPFClusterIsolationProducer

hltEcalPFClusterIsolationProducerRecoRecoChargedCandidate = MuonHLTEcalPFClusterIsolationProducer()
