import FWCore.ParameterSet.Config as cms

hltEgammaHLTHybridClusterProducer = cms.EDProducer('EgammaHLTHybridClusterProducer',
  debugLevel = cms.string('INFO'),
  basicclusterCollection = cms.string(''),
  superclusterCollection = cms.string(''),
  ecalhitcollection = cms.InputTag('ecalRecHit', 'EcalRecHitsEB'),
  l1TagIsolated = cms.InputTag('l1extraParticles', 'Isolated'),
  l1TagNonIsolated = cms.InputTag('l1extraParticles', 'NonIsolated'),
  doIsolated = cms.bool(True),
  l1LowerThr = cms.double(0),
  l1UpperThr = cms.double(9999),
  l1LowerThrIgnoreIsolation = cms.double(999),
  regionEtaMargin = cms.double(0.14),
  regionPhiMargin = cms.double(0.4),
  posCalcParameters = cms.PSet(
    T0_barl = cms.double(7.4),
    T0_endc = cms.double(3.1),
    T0_endcPresh = cms.double(1.2),
    W0 = cms.double(4.2),
    X0 = cms.double(0.89),
    LogWeighted = cms.bool(True)
  ),
  RecHitFlagToBeExcluded = cms.vstring(),
  RecHitSeverityToBeExcluded = cms.vstring(),
  severityRecHitThreshold = cms.double(4),
  HybridBarrelSeedThr = cms.double(1),
  step = cms.int32(10),
  ethresh = cms.double(0.1),
  eseed = cms.double(0.35),
  xi = cms.double(0),
  useEtForXi = cms.bool(True),
  ewing = cms.double(1),
  dynamicEThresh = cms.bool(False),
  eThreshA = cms.double(0.003),
  eThreshB = cms.double(0.1),
  excludeFlagged = cms.bool(False),
  dynamicPhiRoad = cms.bool(False)
)
