import FWCore.ParameterSet.Config as cms

from .EgammaHLTRecoEcalCandidateProducers import EgammaHLTRecoEcalCandidateProducers

hltEgammaHLTRecoEcalCandidateProducers = EgammaHLTRecoEcalCandidateProducers()
