import FWCore.ParameterSet.Config as cms

from .EgammaHLTPixelMatchElectronProducers import EgammaHLTPixelMatchElectronProducers

hltEgammaHLTPixelMatchElectronProducers = EgammaHLTPixelMatchElectronProducers()
