import FWCore.ParameterSet.Config as cms

from .EgammaHLTBcHcalIsolationProducersRegional import EgammaHLTBcHcalIsolationProducersRegional

hltEgammaHLTBcHcalIsolationProducersRegional = EgammaHLTBcHcalIsolationProducersRegional()
