import FWCore.ParameterSet.Config as cms

from .EgammaHLTHcalVarProducerFromRecHit import EgammaHLTHcalVarProducerFromRecHit

hltEgammaHLTHcalVarProducerFromRecHit = EgammaHLTHcalVarProducerFromRecHit()
