import FWCore.ParameterSet.Config as cms

from .EgammaHLTElectronTrackIsolationProducers import EgammaHLTElectronTrackIsolationProducers

hltEgammaHLTElectronTrackIsolationProducers = EgammaHLTElectronTrackIsolationProducers()
