import FWCore.ParameterSet.Config as cms

from .MuonHLTHGCalLayerClusterIsolationProducer import MuonHLTHGCalLayerClusterIsolationProducer

hlthgCalLayerClusterIsolationProducerRecoRecoChargedCandidate = MuonHLTHGCalLayerClusterIsolationProducer()
