import FWCore.ParameterSet.Config as cms

from .MuonHLTHcalPFClusterIsolationProducer import MuonHLTHcalPFClusterIsolationProducer

hltHcalPFClusterIsolationProducerRecoRecoChargedCandidate = MuonHLTHcalPFClusterIsolationProducer()
