import FWCore.ParameterSet.Config as cms

from .EgammaHLTHGCalLayerClusterIsolationProducer import EgammaHLTHGCalLayerClusterIsolationProducer

hlthgCalLayerClusterIsolationProducerRecoRecoEcalCandidate = EgammaHLTHGCalLayerClusterIsolationProducer()
