import FWCore.ParameterSet.Config as cms

from .EgammaHLTHcalPFClusterIsolationProducer import EgammaHLTHcalPFClusterIsolationProducer

hltHcalPFClusterIsolationProducerRecoRecoEcalCandidate = EgammaHLTHcalPFClusterIsolationProducer()
