import FWCore.ParameterSet.Config as cms

from .MuonHLTRechitInRegionsProducer import MuonHLTRechitInRegionsProducer

hltRechitInRegionsProducerRecoRecoChargedCandidate = MuonHLTRechitInRegionsProducer()
