import FWCore.ParameterSet.Config as cms

from .HLTEcalUncalibratedRecHitInAllL1RegionsProducer import HLTEcalUncalibratedRecHitInAllL1RegionsProducer

hltRecHitInAllL1RegionsProducerEcalUncalibratedRecHit = HLTEcalUncalibratedRecHitInAllL1RegionsProducer()
