import FWCore.ParameterSet.Config as cms

from .SiStripBadStripFromQualityDBWriter import SiStripBadStripFromQualityDBWriter

siStripBadStripFromQualityDBWriter = SiStripBadStripFromQualityDBWriter()
