import FWCore.ParameterSet.Config as cms

from .FixedGridRhoProducerFastjetFromRecHit import FixedGridRhoProducerFastjetFromRecHit

fixedGridRhoProducerFastjetFromRecHit = FixedGridRhoProducerFastjetFromRecHit()
