import FWCore.ParameterSet.Config as cms

from .OfflineToTransientBeamSpotESProducer import OfflineToTransientBeamSpotESProducer

offlineToTransientBeamSpotESProducer = OfflineToTransientBeamSpotESProducer()
