import FWCore.ParameterSet.Config as cms

from .SimpleTkTripletWordCandidateFlatTableProducer import SimpleTkTripletWordCandidateFlatTableProducer

simpleTkTripletWordCandidateFlatTableProducer = SimpleTkTripletWordCandidateFlatTableProducer()
