import FWCore.ParameterSet.Config as cms

from .SimpleL1TkJetWordCandidateFlatTableProducer import SimpleL1TkJetWordCandidateFlatTableProducer

simpleL1TkJetWordCandidateFlatTableProducer = SimpleL1TkJetWordCandidateFlatTableProducer()
