import FWCore.ParameterSet.Config as cms

from .HGCalSoALayerClustersProducer_alpaka import HGCalSoALayerClustersProducer_alpaka

hgCalSoALayerClustersProducer = HGCalSoALayerClustersProducer_alpaka()
