import FWCore.ParameterSet.Config as cms

from .CTPPSProtonReconstructionSimulationValidator import CTPPSProtonReconstructionSimulationValidator

ctppsProtonReconstructionSimulationValidatorDefault = CTPPSProtonReconstructionSimulationValidator()
