import FWCore.ParameterSet.Config as cms

from .CTPPSModifiedOpticalFunctionsESSource import CTPPSModifiedOpticalFunctionsESSource

ctppsModifiedOpticalFunctionsESSource = CTPPSModifiedOpticalFunctionsESSource()
