import FWCore.ParameterSet.Config as cms

from .CTPPSProtonReconstructionEfficiencyEstimatorData import CTPPSProtonReconstructionEfficiencyEstimatorData

ctppsProtonReconstructionEfficiencyEstimatorDataDefault = CTPPSProtonReconstructionEfficiencyEstimatorData()
