import FWCore.ParameterSet.Config as cms

from .CTPPSProtonReconstructionEfficiencyEstimatorMC import CTPPSProtonReconstructionEfficiencyEstimatorMC

ctppsProtonReconstructionEfficiencyEstimatorMCDefault = CTPPSProtonReconstructionEfficiencyEstimatorMC()
