import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_HCALRecHitSoAProducer import alpaka_cuda_async_HCALRecHitSoAProducer

alpaka_cuda_asyncHCALRecHitSoAProducer = alpaka_cuda_async_HCALRecHitSoAProducer()
