import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_PFRecHitSoAProducerECAL import alpaka_cuda_async_PFRecHitSoAProducerECAL

alpaka_cuda_asyncPFRecHitSoAProducerECAL = alpaka_cuda_async_PFRecHitSoAProducerECAL()
