import FWCore.ParameterSet.Config as cms

from .MuonBeamspotConstraintValueMapProducer import MuonBeamspotConstraintValueMapProducer

muonBeamspotConstraintValueMapProducer = MuonBeamspotConstraintValueMapProducer()
