import FWCore.ParameterSet.Config as cms

from .SiStripPositionCorrectionsTableProducer import SiStripPositionCorrectionsTableProducer

siStripPositionCorrectionsTable = SiStripPositionCorrectionsTableProducer()
