import FWCore.ParameterSet.Config as cms

from .SiStripLorentzAngleRunInfoTableProducer import SiStripLorentzAngleRunInfoTableProducer

siStripLorentzAngleRunInfoTable = SiStripLorentzAngleRunInfoTableProducer()
