import FWCore.ParameterSet.Config as cms

from .AlignPCLThresholdsLGReader import AlignPCLThresholdsLGReader

edmtestAlignPCLThresholdsReaderAlignPCLThresholdsAlignPCLThresholdsRcd = AlignPCLThresholdsLGReader()
