import FWCore.ParameterSet.Config as cms

from .AlignPCLThresholdsHGReader import AlignPCLThresholdsHGReader

edmtestAlignPCLThresholdsReaderAlignPCLThresholdsHGAlignPCLThresholdsHGRcd = AlignPCLThresholdsHGReader()
