import FWCore.ParameterSet.Config as cms

from .TrackerAdditionalParametersPerDetESModule import TrackerAdditionalParametersPerDetESModule

TrackerAdditionalParametersPerDet = TrackerAdditionalParametersPerDetESModule()
