import FWCore.ParameterSet.Config as cms

from .HLTEgammaGenericQuadraticEtaFilter import HLTEgammaGenericQuadraticEtaFilter

hltEgammaGenericQuadraticEtaFilter = HLTEgammaGenericQuadraticEtaFilter()
