import FWCore.ParameterSet.Config as cms

from .HLTElectronOneOEMinusOneOPFilterRegional import HLTElectronOneOEMinusOneOPFilterRegional

hltElectronOneOEMinusOneOPFilterRegional = HLTElectronOneOEMinusOneOPFilterRegional()
