import FWCore.ParameterSet.Config as cms

from .HLTEgammaTriggerFilterObjectWrapper import HLTEgammaTriggerFilterObjectWrapper

hltEgammaTriggerFilterObjectWrapper = HLTEgammaTriggerFilterObjectWrapper()
