import FWCore.ParameterSet.Config as cms

hltScoutingEgammaProducer = cms.EDProducer('HLTScoutingEgammaProducer',
  EgammaCandidates = cms.InputTag('hltEgammaCandidates'),
  EgammaGsfTracks = cms.InputTag('hltEgammaGsfTracks'),
  SigmaIEtaIEtaMap = cms.InputTag('hltEgammaClusterShape', 'sigmaIEtaIEta5x5'),
  r9Map = cms.InputTag('hltEgammaR9ID', 'r95x5'),
  HoverEMap = cms.InputTag('hltEgammaHoverE'),
  DetaMap = cms.InputTag('hltEgammaGsfTrackVars', 'DetaSeed'),
  DphiMap = cms.InputTag('hltEgammaGsfTrackVars', 'Dphi'),
  MissingHitsMap = cms.InputTag('hltEgammaGsfTrackVars', 'MissingHits'),
  OneOEMinusOneOPMap = cms.InputTag('hltEgammaGsfTrackVars', 'OneOESuperMinusOneOP'),
  EcalPFClusterIsoMap = cms.InputTag('hltEgammaEcalPFClusterIso'),
  EleGsfTrackIsoMap = cms.InputTag('hltEgammaEleGsfTrackIso'),
  HcalPFClusterIsoMap = cms.InputTag('hltEgammaHcalPFClusterIso'),
  egammaPtCut = cms.double(4),
  egammaEtaCut = cms.double(2.5),
  egammaHoverECut = cms.double(1),
  saveRecHitTiming = cms.bool(False),
  mantissaPrecision = cms.int32(10),
  rechitMatrixSize = cms.int32(10),
  ecalRechitEB = cms.InputTag('hltEcalRecHit', 'EcalRecHitsEB'),
  ecalRechitEE = cms.InputTag('hltEcalRecHit', 'EcalRecHitsEE'),
  mightGet = cms.optional.untracked.vstring
)
