import FWCore.ParameterSet.Config as cms

from .FastTrackerRecHitMaskFromSeedProducer import FastTrackerRecHitMaskFromSeedProducer

fastTrackerRecHitMaskFromSeedProducer = FastTrackerRecHitMaskFromSeedProducer()
