import FWCore.ParameterSet.Config as cms

from .SiStripBackPlaneCorrectionDepESProducer import SiStripBackPlaneCorrectionDepESProducer

siStripBackPlaneCorrectionDepESProducer = SiStripBackPlaneCorrectionDepESProducer()
