import FWCore.ParameterSet.Config as cms

hcalHBHEMuon = cms.EDAnalyzer('HcalHBHEMuonAnalyzer',
  hlTriggerResults = cms.InputTag('TriggerResults', '', 'HLT'),
  labelEBRecHit = cms.InputTag('ecalRecHit', 'EcalRecHitsEB'),
  labelEERecHit = cms.InputTag('ecalRecHit', 'EcalRecHitsEE'),
  labelHBHERecHit = cms.InputTag('hbhereco'),
  labelVertex = cms.string('offlinePrimaryVertices'),
  labelMuon = cms.string('muons'),
  triggers = cms.vstring(),
  pMinMuon = cms.double(5),
  verbosity = cms.untracked.int32(0),
  useRaw = cms.int32(0),
  unCorrect = cms.bool(True),
  getCharge = cms.bool(True),
  collapseDepth = cms.bool(False),
  isItPlan1 = cms.bool(False),
  ignoreHECorr = cms.untracked.bool(False),
  isItPreRecHit = cms.untracked.bool(False),
  moduleName = cms.untracked.string(''),
  processName = cms.untracked.string(''),
  maxDepth = cms.untracked.int32(7),
  fileInCorr = cms.untracked.string(''),
  writeRespCorr = cms.untracked.bool(False),
  mightGet = cms.optional.untracked.vstring
)
