import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_AlpakaTestOpaqueAdditionModule import alpaka_cuda_async_AlpakaTestOpaqueAdditionModule

alpaka_cuda_asyncAlpakaTestOpaqueAdditionModule = alpaka_cuda_async_AlpakaTestOpaqueAdditionModule()
