import FWCore.ParameterSet.Config as cms

from .AlpakaTestOpaqueAdditionModule_alpaka import AlpakaTestOpaqueAdditionModule_alpaka

alpakaTestOpaqueAdditionModule = AlpakaTestOpaqueAdditionModule_alpaka()
