import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_AlpakaTestOpaqueAdditionModule import alpaka_rocm_async_AlpakaTestOpaqueAdditionModule

alpaka_rocm_asyncAlpakaTestOpaqueAdditionModule = alpaka_rocm_async_AlpakaTestOpaqueAdditionModule()
