import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_TrackFeatureExtractor import alpaka_cuda_async_TrackFeatureExtractor

alpaka_cuda_asyncTrackFeatureExtractor = alpaka_cuda_async_TrackFeatureExtractor()
