import FWCore.ParameterSet.Config as cms

from .SiPhase2BadStripConfigurableFakeESSource import SiPhase2BadStripConfigurableFakeESSource

siPhase2BadStripConfigurableFakeESSource = SiPhase2BadStripConfigurableFakeESSource()
