import FWCore.ParameterSet.Config as cms

from .LowPtGsfElectronSeedValueMapsProducer import LowPtGsfElectronSeedValueMapsProducer

lowPtGsfElectronSeedValueMaps = LowPtGsfElectronSeedValueMapsProducer()
