import FWCore.ParameterSet.Config as cms

from .TrackingRegionsFromSuperClustersEDProducer import TrackingRegionsFromSuperClustersEDProducer

trackingRegionsFromSuperClusters = TrackingRegionsFromSuperClustersEDProducer()
