import FWCore.ParameterSet.Config as cms

from .TkTransientTrackingRecHitBuilderESProducer import TkTransientTrackingRecHitBuilderESProducer

tkTransientTrackingRecHitBuilderESProducer = TkTransientTrackingRecHitBuilderESProducer()
