import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_HGCalSoALayerClustersProducer import alpaka_rocm_async_HGCalSoALayerClustersProducer

alpaka_rocm_asyncHGCalSoALayerClustersProducer = alpaka_rocm_async_HGCalSoALayerClustersProducer()
