import FWCore.ParameterSet.Config as cms

from .PATTriggerObjectStandAloneSelector import PATTriggerObjectStandAloneSelector

patTriggerObjectStandAloneSelector = PATTriggerObjectStandAloneSelector()
