import FWCore.ParameterSet.Config as cms

from .HLTCaloJetsMatchedToFilteredPFJetsProducer import HLTCaloJetsMatchedToFilteredPFJetsProducer

hltCaloJetsMatchedToFilteredPFJetsProducer = HLTCaloJetsMatchedToFilteredPFJetsProducer()
