import FWCore.ParameterSet.Config as cms

from .HLTCaloJetsMatchedToFilteredCaloJetsProducer import HLTCaloJetsMatchedToFilteredCaloJetsProducer

hltCaloJetsMatchedToFilteredCaloJetsProducer = HLTCaloJetsMatchedToFilteredCaloJetsProducer()
