import FWCore.ParameterSet.Config as cms

from .HLTHcalTowerNoiseCleanerWithrechit import HLTHcalTowerNoiseCleanerWithrechit

hltHcalTowerNoiseCleanerWithrechit = HLTHcalTowerNoiseCleanerWithrechit()
