import FWCore.ParameterSet.Config as cms

from .HLTPFJetCollectionsForLeptonPlusJets import HLTPFJetCollectionsForLeptonPlusJets

hltJetCollectionsForLeptonPlusJetsRecoPFJet = HLTPFJetCollectionsForLeptonPlusJets()
