import FWCore.ParameterSet.Config as cms

from .HLTPFJetCollectionsForBoostedLeptonPlusJets import HLTPFJetCollectionsForBoostedLeptonPlusJets

hltJetCollectionsForBoostedLeptonPlusJetsRecoPFJet = HLTPFJetCollectionsForBoostedLeptonPlusJets()
