import FWCore.ParameterSet.Config as cms

from .HLTCaloJetsCleanedFromLeadingLeptons import HLTCaloJetsCleanedFromLeadingLeptons

hltJetsCleanedFromLeadingLeptonsRecoCaloJet = HLTCaloJetsCleanedFromLeadingLeptons()
