import FWCore.ParameterSet.Config as cms

from .HLTCaloJetCollectionsForElePlusJets import HLTCaloJetCollectionsForElePlusJets

hltJetCollectionsForElePlusJetsRecoCaloJet = HLTCaloJetCollectionsForElePlusJets()
