import FWCore.ParameterSet.Config as cms

from .HLTPFJetCollectionsForElePlusJets import HLTPFJetCollectionsForElePlusJets

hltJetCollectionsForElePlusJetsRecoPFJet = HLTPFJetCollectionsForElePlusJets()
