import FWCore.ParameterSet.Config as cms

from .HLTPFJetsCleanedFromLeadingLeptons import HLTPFJetsCleanedFromLeadingLeptons

hltJetsCleanedFromLeadingLeptonsRecoPFJet = HLTPFJetsCleanedFromLeadingLeptons()
