import FWCore.ParameterSet.Config as cms

from .HLTCaloJetCollectionsForLeptonPlusJets import HLTCaloJetCollectionsForLeptonPlusJets

hltJetCollectionsForLeptonPlusJetsRecoCaloJet = HLTCaloJetCollectionsForLeptonPlusJets()
