import FWCore.ParameterSet.Config as cms

from .HLTPFJetsMatchedToFilteredPFJetsProducer import HLTPFJetsMatchedToFilteredPFJetsProducer

hltpfJetsMatchedToFilteredPFJetsProducer = HLTPFJetsMatchedToFilteredPFJetsProducer()
