import FWCore.ParameterSet.Config as cms

from .HLTPFJetsMatchedToFilteredCaloJetsProducer import HLTPFJetsMatchedToFilteredCaloJetsProducer

hltpfJetsMatchedToFilteredCaloJetsProducer = HLTPFJetsMatchedToFilteredCaloJetsProducer()
