import FWCore.ParameterSet.Config as cms

from .HLTSiPixelClusterMultiplicityValueProducer import HLTSiPixelClusterMultiplicityValueProducer

hltSiPixelClusterMultiplicityValueProducer = HLTSiPixelClusterMultiplicityValueProducer()
