import FWCore.ParameterSet.Config as cms

from .PackedCandidateGenAssociationProducer import PackedCandidateGenAssociationProducer

packedCandidatesGenAssociationDefault = PackedCandidateGenAssociationProducer()
