import FWCore.ParameterSet.Config as cms

from .RecoTrackTrackingParticleAssociationFlatTableProducer import RecoTrackTrackingParticleAssociationFlatTableProducer

recoTrackTrackingParticleAssociationFlatTableProducer = RecoTrackTrackingParticleAssociationFlatTableProducer()
