import FWCore.ParameterSet.Config as cms

from .TrackingParticleRecoTrackAssociationFlatTableProducer import TrackingParticleRecoTrackAssociationFlatTableProducer

trackingParticleRecoTrackAssociationFlatTableProducer = TrackingParticleRecoTrackAssociationFlatTableProducer()
