import FWCore.ParameterSet.Config as cms

from .TrackingParticleNumberOfLayersProducer import TrackingParticleNumberOfLayersProducer

trackingParticleNumberOfLayersProducer = TrackingParticleNumberOfLayersProducer()
