import FWCore.ParameterSet.Config as cms

from .SecondaryVertexTagInfoCategorySelector import SecondaryVertexTagInfoCategorySelector

secondaryVertexTagInfoCategorySelector = SecondaryVertexTagInfoCategorySelector()
