import FWCore.ParameterSet.Config as cms

from .TrackingParticleBHadronRefSelector import TrackingParticleBHadronRefSelector

trackingParticleBHadronRefSelectorDefault = TrackingParticleBHadronRefSelector()
