import FWCore.ParameterSet.Config as cms

from .LayerClustersCollectionTableProducer import LayerClustersCollectionTableProducer

layerClustersCollectionTableProducer = LayerClustersCollectionTableProducer()
