import FWCore.ParameterSet.Config as cms

from .SimClusterCaloParticleFractionFlatTableProducer import SimClusterCaloParticleFractionFlatTableProducer

simClusterCaloParticleFractionFlatTableProducer = SimClusterCaloParticleFractionFlatTableProducer()
