import FWCore.ParameterSet.Config as cms

from .TracksterTracksterEnergyScoreFlatTableProducer import TracksterTracksterEnergyScoreFlatTableProducer

tracksterTracksterEnergyScoreFlatTableProducer = TracksterTracksterEnergyScoreFlatTableProducer()
