import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_PFClusterParamsESProducer import alpaka_cuda_async_PFClusterParamsESProducer

alpaka_cuda_asyncPFClusterParamsESProducer = alpaka_cuda_async_PFClusterParamsESProducer()
