import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_PFClusterSoAProducer import alpaka_rocm_async_PFClusterSoAProducer

alpaka_rocm_asyncPFClusterSoAProducer = alpaka_rocm_async_PFClusterSoAProducer()
