import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_PFClusterParamsESProducer import alpaka_rocm_async_PFClusterParamsESProducer

alpaka_rocm_asyncPFClusterParamsESProducer = alpaka_rocm_async_PFClusterParamsESProducer()
