import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_PFClusterSoAProducer import alpaka_cuda_async_PFClusterSoAProducer

alpaka_cuda_asyncPFClusterSoAProducer = alpaka_cuda_async_PFClusterSoAProducer()
