import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_PFMultiDepthClusterSoAProducer import alpaka_cuda_async_PFMultiDepthClusterSoAProducer

alpaka_cuda_asyncPFMultiDepthClusterSoAProducer = alpaka_cuda_async_PFMultiDepthClusterSoAProducer()
