import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_sistrip_SiStripClusterizerConditionsESProducerAlpaka import alpaka_serial_sync_sistrip_SiStripClusterizerConditionsESProducerAlpaka

alpaka_serial_syncsistripSiStripClusterizerConditionsESProducerAlpaka = alpaka_serial_sync_sistrip_SiStripClusterizerConditionsESProducerAlpaka()
