import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_sistrip_SiStripClusterizerConditionsESProducerAlpaka import alpaka_cuda_async_sistrip_SiStripClusterizerConditionsESProducerAlpaka

alpaka_cuda_asyncsistripSiStripClusterizerConditionsESProducerAlpaka = alpaka_cuda_async_sistrip_SiStripClusterizerConditionsESProducerAlpaka()
