import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_sistrip_SiStripClusterizerConditionsESProducerAlpaka import alpaka_rocm_async_sistrip_SiStripClusterizerConditionsESProducerAlpaka

alpaka_rocm_asyncsistripSiStripClusterizerConditionsESProducerAlpaka = alpaka_rocm_async_sistrip_SiStripClusterizerConditionsESProducerAlpaka()
