import FWCore.ParameterSet.Config as cms

from .SiStripClusterizerConditionsESProducer import SiStripClusterizerConditionsESProducer

SiStripClusterizerConditionsESProducer = SiStripClusterizerConditionsESProducer()
