import FWCore.ParameterSet.Config as cms

from .SiStripClusterizerConditionsGPUESProducer import SiStripClusterizerConditionsGPUESProducer

SiStripClusterizerConditionsGPUESProducer = SiStripClusterizerConditionsGPUESProducer()
