import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_PixelVertexProducerAlpakaPhase1 import alpaka_rocm_async_PixelVertexProducerAlpakaPhase1

alpaka_rocm_asyncPixelVertexProducerAlpakaPhase1 = alpaka_rocm_async_PixelVertexProducerAlpakaPhase1()
