import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_PixelVertexProducerAlpakaHIonPhase1 import alpaka_rocm_async_PixelVertexProducerAlpakaHIonPhase1

alpaka_rocm_asyncPixelVertexProducerAlpakaHIonPhase1 = alpaka_rocm_async_PixelVertexProducerAlpakaHIonPhase1()
