import FWCore.ParameterSet.Config as cms

from .PFJetMETcorrInputProducer import PFJetMETcorrInputProducer

pfJetMETcorrInputProducerTRecoPFJetJetCorrExtractorTRecoPFJet = PFJetMETcorrInputProducer()
