import FWCore.ParameterSet.Config as cms

from .CandidateBoostedDoubleSecondaryVertexESProducer import CandidateBoostedDoubleSecondaryVertexESProducer

candidateBoostedDoubleSecondaryVertexESProducer = CandidateBoostedDoubleSecondaryVertexESProducer()
