import FWCore.ParameterSet.Config as cms

from .CandidateSimpleSecondaryVertexESProducer import CandidateSimpleSecondaryVertexESProducer

candidateSimpleSecondaryVertexESProducer = CandidateSimpleSecondaryVertexESProducer()
