import FWCore.ParameterSet.Config as cms

from .CandidateCombinedSecondaryVertexSoftLeptonESProducer import CandidateCombinedSecondaryVertexSoftLeptonESProducer

candidateCombinedSecondaryVertexSoftLeptonESProducer = CandidateCombinedSecondaryVertexSoftLeptonESProducer()
