import FWCore.ParameterSet.Config as cms

from .CandidateCombinedSecondaryVertexESProducer import CandidateCombinedSecondaryVertexESProducer

candidateCombinedSecondaryVertexESProducer = CandidateCombinedSecondaryVertexESProducer()
