import FWCore.ParameterSet.Config as cms

from .CandidateCombinedSecondaryVertexSoftLeptonCvsLESProducer import CandidateCombinedSecondaryVertexSoftLeptonCvsLESProducer

candidateCombinedSecondaryVertexSoftLeptonCvsLESProducer = CandidateCombinedSecondaryVertexSoftLeptonCvsLESProducer()
