import FWCore.ParameterSet.Config as cms

from .CombinedSecondaryVertexSoftLeptonESProducer import CombinedSecondaryVertexSoftLeptonESProducer

combinedSecondaryVertexSoftLeptonESProducer = CombinedSecondaryVertexSoftLeptonESProducer()
