import FWCore.ParameterSet.Config as cms

from .CITKPFIsolationSumProducerForPUPPI import CITKPFIsolationSumProducerForPUPPI

CITKPFIsolationSumProducerForPUPPI = CITKPFIsolationSumProducerForPUPPI()
