import FWCore.ParameterSet.Config as cms

from .SimpleTriggerL1CaloClusterFlatTableProducer import SimpleTriggerL1CaloClusterFlatTableProducer

simpleTriggerL1CaloClusterFlatTableProducer = SimpleTriggerL1CaloClusterFlatTableProducer()
