import FWCore.ParameterSet.Config as cms

caHitNtupletCUDAPhase2 = cms.EDProducer('CAHitNtupletCUDAPhase2',
  onGPU = cms.bool(True),
  pixelRecHitSrc = cms.InputTag('siPixelRecHitsPreSplittingCUDA'),
  ptmin = cms.double(0.89999997615814209),
  CAThetaCutBarrel = cms.double(0.0020000000949949026),
  CAThetaCutForward = cms.double(0.0030000000260770321),
  hardCurvCut = cms.double(0.032840722495894911),
  dcaCutInnerTriplet = cms.double(0.15000000596046448),
  dcaCutOuterTriplet = cms.double(0.25),
  earlyFishbone = cms.bool(True),
  lateFishbone = cms.bool(False),
  fillStatistics = cms.bool(False),
  minHitsPerNtuplet = cms.uint32(4),
  maxNumberOfDoublets = cms.uint32(2621440),
  minHitsForSharingCut = cms.uint32(10),
  fitNas4 = cms.bool(False),
  doClusterCut = cms.bool(True),
  doZ0Cut = cms.bool(True),
  doPtCut = cms.bool(True),
  useRiemannFit = cms.bool(False),
  doSharedHitCut = cms.bool(True),
  dupPassThrough = cms.bool(False),
  useSimpleTripletCleaner = cms.bool(True),
  idealConditions = cms.bool(False),
  includeFarForwards = cms.bool(True),
  includeJumpingForwardDoublets = cms.bool(True),
  trackQualityCuts = cms.PSet(
    maxChi2 = cms.double(5),
    minPt = cms.double(0.5),
    maxTip = cms.double(0.3),
    maxZip = cms.double(12)
  ),
  mightGet = cms.optional.untracked.vstring
)
