import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_TestAlpakaGlobalProducerOffset import alpaka_cuda_async_TestAlpakaGlobalProducerOffset

alpaka_cuda_asyncTestAlpakaGlobalProducerOffset = alpaka_cuda_async_TestAlpakaGlobalProducerOffset()
