import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_TestAlpakaProducer import alpaka_rocm_async_TestAlpakaProducer

alpaka_rocm_asyncTestAlpakaProducer = alpaka_rocm_async_TestAlpakaProducer()
