import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_TestAlpakaStreamFixedQueueProducer import alpaka_rocm_async_TestAlpakaStreamFixedQueueProducer

alpaka_rocm_asyncTestAlpakaStreamFixedQueueProducer = alpaka_rocm_async_TestAlpakaStreamFixedQueueProducer()
