import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_TestAlpakaStreamSynchronizingProducerToDevice import alpaka_serial_sync_TestAlpakaStreamSynchronizingProducerToDevice

alpaka_serial_syncTestAlpakaStreamSynchronizingProducerToDevice = alpaka_serial_sync_TestAlpakaStreamSynchronizingProducerToDevice()
