import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_TestAlpakaGlobalProducerImplicitCopyToDevice import alpaka_cuda_async_TestAlpakaGlobalProducerImplicitCopyToDevice

alpaka_cuda_asyncTestAlpakaGlobalProducerImplicitCopyToDevice = alpaka_cuda_async_TestAlpakaGlobalProducerImplicitCopyToDevice()
