import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_TestAlpakaGlobalProducerE import alpaka_cuda_async_TestAlpakaGlobalProducerE

alpaka_cuda_asyncTestAlpakaGlobalProducerE = alpaka_cuda_async_TestAlpakaGlobalProducerE()
