import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_TestAlpakaESProducerAMulti import alpaka_rocm_async_TestAlpakaESProducerAMulti

alpaka_rocm_asyncTestAlpakaESProducerAMulti = alpaka_rocm_async_TestAlpakaESProducerAMulti()
