import FWCore.ParameterSet.Config as cms

from .TestAlpakaStreamSynchronizingProducer_alpaka import TestAlpakaStreamSynchronizingProducer_alpaka

testAlpakaStreamSynchronizingProducer = TestAlpakaStreamSynchronizingProducer_alpaka()
