import FWCore.ParameterSet.Config as cms

from .TestAlpakaGlobalProducerOffset_alpaka import TestAlpakaGlobalProducerOffset_alpaka

testAlpakaGlobalProducerOffset = TestAlpakaGlobalProducerOffset_alpaka()
