import FWCore.ParameterSet.Config as cms

def JetAnalyzer(*args, **kwargs):
  mod = cms.EDProducer('JetAnalyzer',
    JetType = cms.string('calo'),
    JetCorrections = cms.InputTag('dqmAk4CaloL2L3ResidualCorrector'),
    jetsrc = cms.InputTag('ak4CaloJets'),
    METCollectionLabel = cms.InputTag('caloMet'),
    muonsrc = cms.InputTag('muons'),
    srcRho = cms.InputTag(''),
    l1algoname = cms.string('L1Tech_BPTX_plus_AND_minus.v0'),
    filljetHighLevel = cms.bool(False),
    fillsubstructure = cms.bool(False),
    ptMinBoosted = cms.double(400),
    stage2L1 = cms.bool(False),
    highPtJetTrigger = cms.PSet(
      ReadPrescalesFromFile = cms.bool(False),
      andOr = cms.bool(False),
      andOrDcs = cms.bool(False),
      andOrHlt = cms.bool(False),
      andOrL1 = cms.bool(False),
      errorReplyDcs = cms.bool(False),
      errorReplyHlt = cms.bool(False),
      errorReplyL1 = cms.bool(False),
      l1BeforeMask = cms.bool(False),
      stage2 = cms.bool(False),
      dcsInputTag = cms.InputTag('scalersRawToDigi'),
      dcsRecordInputTag = cms.InputTag('onlineMetaDataDigis'),
      hltInputTag = cms.InputTag('TriggerResults', '', 'HLT'),
      l1tAlgBlkInputTag = cms.InputTag('gtStage2Digis'),
      l1tExtBlkInputTag = cms.InputTag('gtStage2Digis'),
      dbLabel = cms.string(''),
      hltDBKey = cms.string(''),
      dcsPartitions = cms.vint32(),
      hltPaths = cms.vstring(),
      l1Algorithms = cms.vstring(),
      verbosityLevel = cms.uint32(0)
    ),
    lowPtJetTrigger = cms.PSet(
      ReadPrescalesFromFile = cms.bool(False),
      andOr = cms.bool(False),
      andOrDcs = cms.bool(False),
      andOrHlt = cms.bool(False),
      andOrL1 = cms.bool(False),
      errorReplyDcs = cms.bool(False),
      errorReplyHlt = cms.bool(False),
      errorReplyL1 = cms.bool(False),
      l1BeforeMask = cms.bool(False),
      stage2 = cms.bool(False),
      dcsInputTag = cms.InputTag('scalersRawToDigi'),
      dcsRecordInputTag = cms.InputTag('onlineMetaDataDigis'),
      hltInputTag = cms.InputTag('TriggerResults', '', 'HLT'),
      l1tAlgBlkInputTag = cms.InputTag('gtStage2Digis'),
      l1tExtBlkInputTag = cms.InputTag('gtStage2Digis'),
      dbLabel = cms.string(''),
      hltDBKey = cms.string(''),
      dcsPartitions = cms.vint32(),
      hltPaths = cms.vstring(),
      l1Algorithms = cms.vstring(),
      verbosityLevel = cms.uint32(0)
    ),
    TriggerResultsLabel = cms.InputTag('TriggerResults', '', 'HLT'),
    processname = cms.string('HLT'),
    JetCleaningFlag = cms.untracked.bool(False),
    runcosmics = cms.untracked.bool(False),
    CleaningParameters = cms.PSet(
      gtLabel = cms.InputTag('gtDigis'),
      trigSelection = cms.PSet(
        andOr = cms.bool(False),
        hltInputTag = cms.InputTag('TriggerResults', '', 'HLT'),
        hltDBKey = cms.string('jetmet_hltsel'),
        hltPaths = cms.vstring(''),
        andOrHlt = cms.bool(False),
        errorReplyHlt = cms.bool(False)
      ),
      bypassAllPVChecks = cms.bool(True),
      bypassAllDCSChecks = cms.bool(False),
      vertexCollection = cms.InputTag('goodOfflinePrimaryVerticesDQM')
    ),
    InputJetIDValueMap = cms.InputTag('ak4JetID'),
    JetIDQuality = cms.string('LOOSE'),
    JetIDVersion = cms.string('PURE09'),
    InputMVAPUIDDiscriminant = cms.InputTag('pileupJetIdEvaluatorDQM', 'fullDiscriminant'),
    InputCutPUIDDiscriminant = cms.InputTag('pileupJetIdEvaluatorDQM', 'cutbasedDiscriminant'),
    InputMVAPUIDValue = cms.InputTag('pileupJetIdEvaluatorDQM', 'fullId'),
    InputCutPUIDValue = cms.InputTag('pileupJetIdEvaluatorDQM', 'cutbasedId'),
    InputQGMultiplicity = cms.InputTag('QGTagger', 'mult'),
    InputQGLikelihood = cms.InputTag('QGTagger', 'qgLikelihood'),
    InputQGPtDToken = cms.InputTag('QGTagger', 'ptD'),
    InputQGAxis2 = cms.InputTag('QGTagger', 'axis2'),
    fillCHShistos = cms.bool(False),
    jetAnalysis = cms.PSet(
      verbose = cms.int32(0),
      eBin = cms.int32(100),
      eMax = cms.double(1000),
      eMin = cms.double(0),
      etaBin = cms.int32(100),
      etaMax = cms.double(5),
      etaMin = cms.double(-5),
      pBin = cms.int32(100),
      pMax = cms.double(500),
      pMin = cms.double(0),
      phiBin = cms.int32(70),
      phiMax = cms.double(3.2),
      phiMin = cms.double(-3.2),
      ptBin = cms.int32(100),
      ptMax = cms.double(500),
      ptMin = cms.double(20),
      pVBin = cms.int32(100),
      pVMax = cms.double(100),
      pVMin = cms.double(0),
      ptThreshold = cms.double(20),
      ptThresholdUnc = cms.double(30),
      asymmetryThirdJetCut = cms.double(30),
      balanceThirdJetCut = cms.double(0.2),
      fillJIDPassFrac = cms.int32(1)
    ),
    DCSFilterForJetMonitoring = cms.PSet(
      DebugOn = cms.untracked.bool(False),
      DetectorTypes = cms.untracked.string('ecal:hcal'),
      alwaysPass = cms.untracked.bool(False),
      scalerSrc = cms.untracked.InputTag('scalersRawToDigi'),
      onlineMetaDataDigisSrc = cms.untracked.InputTag('onlineMetaDataDigis')
    ),
    mightGet = cms.optional.untracked.vstring
  )
  for a in args:
    mod.update_(a)
  mod.update_(kwargs)
  return mod
