import FWCore.ParameterSet.Config as cms

from .ParticleTransformerAK4ONNXJetTagsProducer import ParticleTransformerAK4ONNXJetTagsProducer

pfParticleTransformerAK4JetTags = ParticleTransformerAK4ONNXJetTagsProducer()
