import FWCore.ParameterSet.Config as cms

from .HLTDiPFJetPlusTausCandidatePFJetProducer import HLTDiPFJetPlusTausCandidatePFJetProducer

hltDiPFJetPlusTausCandidatePFJetProducer = HLTDiPFJetPlusTausCandidatePFJetProducer()
