import FWCore.ParameterSet.Config as cms

from .HLTPFTauPairLeadTrackDzMatchFilter import HLTPFTauPairLeadTrackDzMatchFilter

hltPFTauPairLeadTrackDzMatchFilter = HLTPFTauPairLeadTrackDzMatchFilter()
