import FWCore.ParameterSet.Config as cms

from .TauRegionalPixelSeedTrackingRegionEDProducer import TauRegionalPixelSeedTrackingRegionEDProducer

tauRegionalPixelSeedTrackingRegions = TauRegionalPixelSeedTrackingRegionEDProducer()
