import FWCore.ParameterSet.Config as cms

from .TruthBranchCaloAssociationProducer import TruthBranchCaloAssociationProducer

truthBranchCaloAssociationProducer = TruthBranchCaloAssociationProducer()
