import FWCore.ParameterSet.Config as cms

from .TruthBranchTrackingAssociationProducer import TruthBranchTrackingAssociationProducer

truthBranchTrackingAssociationProducer = TruthBranchTrackingAssociationProducer()
