import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_MPIReceiverPortable import alpaka_rocm_async_MPIReceiverPortable

alpaka_rocm_asyncMPIReceiverPortable = alpaka_rocm_async_MPIReceiverPortable()
