import FWCore.ParameterSet.Config as cms

HGCalTBAnalyzer = cms.EDAnalyzer('HGCalTBAnalyzer',
  DetectorEE = cms.string('HGCalEESensitive'),
  UseEE = cms.bool(True),
  ZFrontEE = cms.double(0),
  CaloHitSrcEE = cms.string('HGCHitsEE'),
  DigiSrcEE = cms.InputTag('mix', 'HGCDigisEE'),
  RecHitSrcEE = cms.InputTag('HGCalRecHit', 'HGCEERecHits'),
  DetectorFH = cms.string('HGCalHESiliconSensitive'),
  UseFH = cms.bool(False),
  ZFrontFH = cms.double(0),
  CaloHitSrcFH = cms.string('HGCHitsHEfront'),
  DigiSrcFH = cms.InputTag('mix', 'HGCDigisHEfront'),
  RecHitSrcFH = cms.InputTag('HGCalRecHit', 'HGCHEFRecHits'),
  DetectorBH = cms.string('AHCal'),
  UseBH = cms.bool(False),
  ZFrontBH = cms.double(0),
  CaloHitSrcBH = cms.string('HcalHits'),
  DigiSrcBH = cms.InputTag('mix', 'HGCDigisHEback'),
  RecHitSrcBH = cms.InputTag('HGCalRecHit', 'HGCHEBRecHits'),
  DetectorBeam = cms.string('HcalTB06BeamDetector'),
  UseBeam = cms.bool(False),
  CaloHitSrcBeam = cms.string('HcalTB06BeamHits'),
  IDBeams = cms.vint32(
    1000,
    1001,
    1002,
    1003,
    1004,
    1005,
    1006,
    1007,
    1008,
    1011,
    1012,
    1013,
    1014,
    2001,
    2002,
    2003,
    2004,
    2005
  ),
  GeneratorSrc = cms.InputTag('generatorSmeared'),
  HGCPassiveEE = cms.InputTag('g4SimHits', 'HGCalEEPassiveHits'),
  HGCPassiveFH = cms.InputTag('g4SimHits', 'HGCalHEPassiveHits'),
  HGCPassiveBH = cms.InputTag('g4SimHits', 'HGCalAHPassiveHits'),
  HGCPassiveCMSE = cms.InputTag('g4SimHits', 'CMSEPassiveHits'),
  DoSimHits = cms.bool(True),
  DoDigis = cms.bool(True),
  DoRecHits = cms.bool(True),
  SampleIndex = cms.int32(0),
  DoTree = cms.untracked.bool(True),
  DoTreeCell = cms.untracked.bool(True),
  DoPassive = cms.untracked.bool(False)
)
