import FWCore.ParameterSet.Config as cms

hgcalElectronIDValueMap = cms.EDProducer('HGCalElectronIDValueMapProducer',
  electrons = cms.InputTag('ecalDrivenGsfElectronsFromMultiCl'),
  pcaRadius = cms.double(3),
  variables = cms.vstring(
    'ecOrigEt',
    'ecOrigEnergy',
    'ecEt',
    'ecEnergy',
    'ecEnergyEE',
    'ecEnergyFH',
    'ecEnergyBH',
    'pcaEig1',
    'pcaEig2',
    'pcaEig3',
    'pcaSig1',
    'pcaSig2',
    'pcaSig3',
    'pcaAxisX',
    'pcaAxisY',
    'pcaAxisZ',
    'pcaPositionX',
    'pcaPositionY',
    'pcaPositionZ',
    'sigmaUU',
    'sigmaVV',
    'sigmaEE',
    'sigmaPP',
    'nLayers',
    'firstLayer',
    'lastLayer',
    'e4oEtot',
    'layerEfrac10',
    'layerEfrac90',
    'measuredDepth',
    'expectedDepth',
    'expectedSigma',
    'depthCompatibility',
    'caloIsoRing0',
    'caloIsoRing1',
    'caloIsoRing2',
    'caloIsoRing3',
    'caloIsoRing4'
  ),
  isoNRings = cms.uint32(5),
  isoDeltaR = cms.double(0.15),
  isoDeltaRmin = cms.double(0),
  EERecHits = cms.InputTag('HGCalRecHit', 'HGCEERecHits'),
  FHRecHits = cms.InputTag('HGCalRecHit', 'HGCHEFRecHits'),
  BHRecHits = cms.InputTag('HGCalRecHit', 'HGCHEBRecHits')
)
