import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_ngt_GenericClonerPortable import alpaka_rocm_async_ngt_GenericClonerPortable

alpaka_rocm_asyncngtGenericClonerPortable = alpaka_rocm_async_ngt_GenericClonerPortable()
