import FWCore.ParameterSet.Config as cms

from .MuonTransientTrackingRecHitBuilderESProducer import MuonTransientTrackingRecHitBuilderESProducer

muonTransientTrackingRecHitBuilderESProducer = MuonTransientTrackingRecHitBuilderESProducer()
