import FWCore.ParameterSet.Config as cms

from .CrossingFramePSimHitToPSimHitsConverter import CrossingFramePSimHitToPSimHitsConverter

crossingFramePSimHitToPSimHits = CrossingFramePSimHitToPSimHitsConverter()
