import FWCore.ParameterSet.Config as cms

from .MultiClustersFromTrackstersProducer import MultiClustersFromTrackstersProducer

multiClustersFromTrackstersProducer = MultiClustersFromTrackstersProducer()
