import FWCore.ParameterSet.Config as cms

from .TICLCandidateFromTrackstersProducer import TICLCandidateFromTrackstersProducer

ticlCandidateFromTrackstersProducer = TICLCandidateFromTrackstersProducer()
