import FWCore.ParameterSet.Config as cms

trackstersProducer = cms.EDProducer('TrackstersProducer',
  layer_clusters = cms.InputTag('hgcalLayerClusters'),
  filtered_mask = cms.InputTag('filteredLayerClusters', 'iterationLabelGoesHere'),
  original_mask = cms.InputTag('hgcalLayerClusters', 'InitialLayerClustersMask'),
  time_layerclusters = cms.InputTag('hgcalLayerClusters', 'timeLayerCluster'),
  layer_clusters_tiles = cms.InputTag('ticlLayerTileProducer'),
  seeding_regions = cms.InputTag('ticlSeedingRegionProducer'),
  algo_verbosity = cms.int32(0),
  min_cos_theta = cms.double(0.915),
  min_cos_pointing = cms.double(-1),
  missing_layers = cms.int32(0),
  min_clusters_per_ntuplet = cms.int32(10),
  max_delta_time = cms.double(3),
  out_in_dfs = cms.bool(True),
  max_out_in_hops = cms.int32(10),
  eid_graph_path = cms.string('RecoHGCal/TICL/data/tf_models/energy_id_v0.pb'),
  eid_input_name = cms.string('input'),
  eid_output_name_energy = cms.string('output/regressed_energy'),
  eid_output_name_id = cms.string('output/id_probabilities'),
  eid_min_cluster_energy = cms.double(1),
  eid_n_layers = cms.int32(50),
  eid_n_clusters = cms.int32(10),
  mightGet = cms.optional.untracked.vstring
)
