import FWCore.ParameterSet.Config as cms

trackstersMergeProducer = cms.EDProducer('TrackstersMergeProducer',
  trackstersem = cms.InputTag('ticlTrackstersEM'),
  tracksterstrk = cms.InputTag('ticlTrackstersTrk'),
  trackstershad = cms.InputTag('ticlTrackstersHAD'),
  seedingTrk = cms.InputTag('ticlSeedingTrk'),
  layer_clusters = cms.InputTag('hgcalLayerClusters'),
  tracks = cms.InputTag('generalTracks'),
  optimiseAcrossTracksters = cms.bool(True),
  eta_bin_window = cms.int32(1),
  phi_bin_window = cms.int32(1),
  pt_sigma_high = cms.double(2),
  pt_sigma_low = cms.double(2),
  cosangle_align = cms.double(0.9945),
  e_over_h_threshold = cms.double(1),
  pt_neutral_threshold = cms.double(2),
  resol_calo_offset = cms.double(1.5),
  resol_calo_scale = cms.double(0.15),
  debug = cms.bool(True),
  eid_graph_path = cms.string('RecoHGCal/TICL/data/tf_models/energy_id_v0.pb'),
  eid_input_name = cms.string('input'),
  eid_output_name_energy = cms.string('output/regressed_energy'),
  eid_output_name_id = cms.string('output/id_probabilities'),
  eid_min_cluster_energy = cms.double(1),
  eid_n_layers = cms.int32(50),
  eid_n_clusters = cms.int32(10),
  mightGet = cms.optional.untracked.vstring
)
