import FWCore.ParameterSet.Config as cms

from .HLTParticleTransformerAK4TagInfoProducer import HLTParticleTransformerAK4TagInfoProducer

hltParticleTransformerAK4TagInfoProducer = HLTParticleTransformerAK4TagInfoProducer()
