import FWCore.ParameterSet.Config as cms

from .ParticleTransformerAK4TagInfoProducer import ParticleTransformerAK4TagInfoProducer

pfParticleTransformerAK4TagInfos = ParticleTransformerAK4TagInfoProducer()
