import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_hgcal_HGCalMappingModuleESProducer import alpaka_cuda_async_hgcal_HGCalMappingModuleESProducer

alpaka_cuda_asynchgcalHGCalMappingModuleESProducer = alpaka_cuda_async_hgcal_HGCalMappingModuleESProducer()
