import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_hgcal_HGCalDenseIndexTriggerInfoESProducer import alpaka_rocm_async_hgcal_HGCalDenseIndexTriggerInfoESProducer

alpaka_rocm_asynchgcalHGCalDenseIndexTriggerInfoESProducer = alpaka_rocm_async_hgcal_HGCalDenseIndexTriggerInfoESProducer()
