import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_hgcal_HGCalMappingCellESProducer import alpaka_serial_sync_hgcal_HGCalMappingCellESProducer

alpaka_serial_synchgcalHGCalMappingCellESProducer = alpaka_serial_sync_hgcal_HGCalMappingCellESProducer()
