import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_hgcal_HGCalMappingTriggerModuleESProducer import alpaka_serial_sync_hgcal_HGCalMappingTriggerModuleESProducer

alpaka_serial_synchgcalHGCalMappingTriggerModuleESProducer = alpaka_serial_sync_hgcal_HGCalMappingTriggerModuleESProducer()
