import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_hgcal_HGCalMappingModuleESProducer import alpaka_rocm_async_hgcal_HGCalMappingModuleESProducer

alpaka_rocm_asynchgcalHGCalMappingModuleESProducer = alpaka_rocm_async_hgcal_HGCalMappingModuleESProducer()
