import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_hgcal_HGCalMappingCellESProducer import alpaka_rocm_async_hgcal_HGCalMappingCellESProducer

alpaka_rocm_asynchgcalHGCalMappingCellESProducer = alpaka_rocm_async_hgcal_HGCalMappingCellESProducer()
