import FWCore.ParameterSet.Config as cms

from .SiPixelLorentzAnglePCLHarvesterMCS import SiPixelLorentzAnglePCLHarvesterMCS

siPixelLorentzAnglePCLHarvesterMCS = SiPixelLorentzAnglePCLHarvesterMCS()
