import FWCore.ParameterSet.Config as cms

from .EcalPhiSymRecHitFlatTableProducerLumi import EcalPhiSymRecHitFlatTableProducerLumi

ecalPhiSymRecHitFlatTableProducerLumi = EcalPhiSymRecHitFlatTableProducerLumi()
