import FWCore.ParameterSet.Config as cms

from .EcalPhiSymInfoFlatTableProducerLumi import EcalPhiSymInfoFlatTableProducerLumi

ecalPhiSymInfoFlatTableProducerLumi = EcalPhiSymInfoFlatTableProducerLumi()
