import FWCore.ParameterSet.Config as cms

from .TPIsolatedPFCandidatesOnPFCandidates import TPIsolatedPFCandidatesOnPFCandidates

tpIsolatedPFCandidatesOnPFCandidates = TPIsolatedPFCandidatesOnPFCandidates()
