import FWCore.ParameterSet.Config as cms

from .TPPFCandidatesOnPileUpPFCandidates import TPPFCandidatesOnPileUpPFCandidates

tppfCandidatesOnPileUpPFCandidates = TPPFCandidatesOnPileUpPFCandidates()
