import FWCore.ParameterSet.Config as cms

from .TPPileUpPFCandidatesOnPFCandidates import TPPileUpPFCandidatesOnPFCandidates

tpPileUpPFCandidatesOnPFCandidates = TPPileUpPFCandidatesOnPFCandidates()
