import FWCore.ParameterSet.Config as cms

from .AssociatedVariableMaxCutCandRefSelector import AssociatedVariableMaxCutCandRefSelector

associatedVariableMaxCutCandRefSelector = AssociatedVariableMaxCutCandRefSelector()
