import FWCore.ParameterSet.Config as cms

from .AssociatedVariableMaxCutCandViewSelector import AssociatedVariableMaxCutCandViewSelector

associatedVariableMaxCutCandViewSelector = AssociatedVariableMaxCutCandViewSelector()
