import FWCore.ParameterSet.Config as cms

from .AssociatedVariableMaxCutCandSelectorNew import AssociatedVariableMaxCutCandSelectorNew

associatedVariableMaxCutCandSelectorNew = AssociatedVariableMaxCutCandSelectorNew()
