import FWCore.ParameterSet.Config as cms

from .AssociatedVariableMaxCutCandSelector import AssociatedVariableMaxCutCandSelector

associatedVariableMaxCutCandSelector = AssociatedVariableMaxCutCandSelector()
