import FWCore.ParameterSet.Config as cms

from .PtMinAssociatedVariableMaxCutCandSelector import PtMinAssociatedVariableMaxCutCandSelector

ptMinAssociatedVariableMaxCutCandSelector = PtMinAssociatedVariableMaxCutCandSelector()
