import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_HcalDigisSoAProducer import alpaka_rocm_async_HcalDigisSoAProducer

alpaka_rocm_asyncHcalDigisSoAProducer = alpaka_rocm_async_HcalDigisSoAProducer()
