import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_HcalDigisSoAProducer import alpaka_serial_sync_HcalDigisSoAProducer

alpaka_serial_syncHcalDigisSoAProducer = alpaka_serial_sync_HcalDigisSoAProducer()
