import FWCore.ParameterSet.Config as cms

from .HcalElectronicsMappingGPUESProducer import HcalElectronicsMappingGPUESProducer

hcalElectronicsMappingGPUESProducer = HcalElectronicsMappingGPUESProducer()
