import FWCore.ParameterSet.Config as cms

from .PFDisplacedVertexCandidateProducer import PFDisplacedVertexCandidateProducer

particleFlowDisplacedVertexCandidate = PFDisplacedVertexCandidateProducer()
