import FWCore.ParameterSet.Config as cms

from .IsolatedEcalPixelTrackCandidateProducer import IsolatedEcalPixelTrackCandidateProducer

isolEcalPixelTrackProd = IsolatedEcalPixelTrackCandidateProducer()
