import FWCore.ParameterSet.Config as cms

from .MaskedMeasurementTrackerEventProducer import MaskedMeasurementTrackerEventProducer

maskedMeasurementTrackerEventProducer = MaskedMeasurementTrackerEventProducer()
