import FWCore.ParameterSet.Config as cms

from .SimpleCandidateCollectionFlatTableProducer import SimpleCandidateCollectionFlatTableProducer

simpleCandidateCollectionFlatTableProducer = SimpleCandidateCollectionFlatTableProducer()
