import FWCore.ParameterSet.Config as cms

from .SimplePFTauCandidateFlatTableProducer import SimplePFTauCandidateFlatTableProducer

simplePFTauCandidateFlatTableProducer = SimplePFTauCandidateFlatTableProducer()
