import FWCore.ParameterSet.Config as cms

from .SimpleCompositeCandidateFlatTableProducer import SimpleCompositeCandidateFlatTableProducer

simpleCompositeCandidateFlatTableProducer = SimpleCompositeCandidateFlatTableProducer()
