import FWCore.ParameterSet.Config as cms

from .SimpleRun3ScoutingTrackFlatTableProducer import SimpleRun3ScoutingTrackFlatTableProducer

simpleRun3ScoutingTrackFlatTableProducer = SimpleRun3ScoutingTrackFlatTableProducer()
