import FWCore.ParameterSet.Config as cms

from .SimpleTriggerTrackFlatTableProducer import SimpleTriggerTrackFlatTableProducer

simpleTriggerTrackFlatTableProducer = SimpleTriggerTrackFlatTableProducer()
