import FWCore.ParameterSet.Config as cms

from .SimpleGenParticleFlatTableProducer import SimpleGenParticleFlatTableProducer

simpleGenParticleFlatTableProducer = SimpleGenParticleFlatTableProducer()
