import FWCore.ParameterSet.Config as cms

from .SimplePATElectronFlatTableProducer import SimplePATElectronFlatTableProducer

simplePATElectronFlatTableProducer = SimplePATElectronFlatTableProducer()
