import FWCore.ParameterSet.Config as cms

from .SimplePATCandidateFlatTableProducer import SimplePATCandidateFlatTableProducer

simplePATCandidateFlatTableProducer = SimplePATCandidateFlatTableProducer()
