import FWCore.ParameterSet.Config as cms

from .SimpleSecondaryVertexFlatTableProducer import SimpleSecondaryVertexFlatTableProducer

simpleSecondaryVertexFlatTableProducer = SimpleSecondaryVertexFlatTableProducer()
