import FWCore.ParameterSet.Config as cms

from .SimpleSuperclusterFlatTableProducer import SimpleSuperclusterFlatTableProducer

simpleSuperclusterFlatTableProducer = SimpleSuperclusterFlatTableProducer()
