import FWCore.ParameterSet.Config as cms

from .SimplePATIsolatedTrackFlatTableProducer import SimplePATIsolatedTrackFlatTableProducer

simplePATIsolatedTrackFlatTableProducer = SimplePATIsolatedTrackFlatTableProducer()
