import FWCore.ParameterSet.Config as cms

from .SimpleOnlineLuminosityFlatTableProducer import SimpleOnlineLuminosityFlatTableProducer

simpleOnlineLuminosityFlatTableProducer = SimpleOnlineLuminosityFlatTableProducer()
