import FWCore.ParameterSet.Config as cms

from .SimplePFCandidateFlatTableProducer import SimplePFCandidateFlatTableProducer

simplePFCandidateFlatTableProducer = SimplePFCandidateFlatTableProducer()
