import FWCore.ParameterSet.Config as cms

from .SimpleTrajectorySeedFlatTableProducer import SimpleTrajectorySeedFlatTableProducer

simpleTrajectorySeedFlatTableProducer = SimpleTrajectorySeedFlatTableProducer()
