import FWCore.ParameterSet.Config as cms

from .SimpleProtonTrackFlatTableProducer import SimpleProtonTrackFlatTableProducer

simpleProtonTrackFlatTableProducer = SimpleProtonTrackFlatTableProducer()
