import FWCore.ParameterSet.Config as cms

from .SimpleTriggerL1EGFlatTableProducer import SimpleTriggerL1EGFlatTableProducer

simpleTriggerL1EGFlatTableProducer = SimpleTriggerL1EGFlatTableProducer()
