import FWCore.ParameterSet.Config as cms

from .SimplePatJetConstituentTableProducer import SimplePatJetConstituentTableProducer

simplePatJetConstituentTableProducer = SimplePatJetConstituentTableProducer()
