import FWCore.ParameterSet.Config as cms

from .SimpleTriggerL1EtSumFlatTableProducer import SimpleTriggerL1EtSumFlatTableProducer

simpleTriggerL1EtSumFlatTableProducer = SimpleTriggerL1EtSumFlatTableProducer()
