import FWCore.ParameterSet.Config as cms

from .SimplePATGenParticleFlatTableProducer import SimplePATGenParticleFlatTableProducer

simplePATGenParticleFlatTableProducer = SimplePATGenParticleFlatTableProducer()
