import FWCore.ParameterSet.Config as cms

from .SimpleTriggerL1TkMuonFlatTableProducer import SimpleTriggerL1TkMuonFlatTableProducer

simpleTriggerL1TkMuonFlatTableProducer = SimpleTriggerL1TkMuonFlatTableProducer()
