import FWCore.ParameterSet.Config as cms

from .SimpleGenFilterFlatTableProducerLumi import SimpleGenFilterFlatTableProducerLumi

simpleGenFilterFlatTableProducerLumi = SimpleGenFilterFlatTableProducerLumi()
