import FWCore.ParameterSet.Config as cms

from .SimplePATGenericParticleFlatTableProducer import SimplePATGenericParticleFlatTableProducer

simplePATGenericParticleFlatTableProducer = SimplePATGenericParticleFlatTableProducer()
