import FWCore.ParameterSet.Config as cms

from .SimpleGenJetConstituentTableProducer import SimpleGenJetConstituentTableProducer

simpleGenJetConstituentTableProducer = SimpleGenJetConstituentTableProducer()
