import FWCore.ParameterSet.Config as cms

from .ChargedHadronPFTrackIsolationProducer import ChargedHadronPFTrackIsolationProducer

chargedHadronPFTrackIsolation = ChargedHadronPFTrackIsolationProducer()
