import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_HcalRecoParamWithPulseShapeESProducer import alpaka_serial_sync_HcalRecoParamWithPulseShapeESProducer

alpaka_serial_syncHcalRecoParamWithPulseShapeESProducer = alpaka_serial_sync_HcalRecoParamWithPulseShapeESProducer()
