import FWCore.ParameterSet.Config as cms

from .AlpakaTestWrapperAdditionModule_alpaka import AlpakaTestWrapperAdditionModule_alpaka

alpakaTestWrapperAdditionModule = AlpakaTestWrapperAdditionModule_alpaka()
