import FWCore.ParameterSet.Config as cms

from .PixelFEDChannelCollectionMapTestReader import PixelFEDChannelCollectionMapTestReader

PixelFEDChannelCollectionMapTestReader = PixelFEDChannelCollectionMapTestReader()
