import FWCore.ParameterSet.Config as cms

from .SiPixelGainCalibrationForHLTGPUESProducer import SiPixelGainCalibrationForHLTGPUESProducer

siPixelGainCalibrationForHLTGPU = SiPixelGainCalibrationForHLTGPUESProducer()
