import FWCore.ParameterSet.Config as cms

from .SiPixelROCsStatusAndMappingWrapperESProducer import SiPixelROCsStatusAndMappingWrapperESProducer

siPixelROCsStatusAndMappingWrapperESProducer = SiPixelROCsStatusAndMappingWrapperESProducer()
