import FWCore.ParameterSet.Config as cms

from .SiPixelFakeTemplateDBObjectESSource import SiPixelFakeTemplateDBObjectESSource

siPixelFakeTemplateDBObjectESSource = SiPixelFakeTemplateDBObjectESSource()
