import FWCore.ParameterSet.Config as cms

from .SiPixelFakeGenErrorDBObjectESSource import SiPixelFakeGenErrorDBObjectESSource

siPixelFakeGenErrorDBObjectESSource = SiPixelFakeGenErrorDBObjectESSource()
