import FWCore.ParameterSet.Config as cms

from .ZMuMuMassConstraintParameterFinder import ZMuMuMassConstraintParameterFinder

zMuMuMassConstraintParameterFinder = ZMuMuMassConstraintParameterFinder()
