import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_SiPixelPhase2DigiToCluster import alpaka_serial_sync_SiPixelPhase2DigiToCluster

alpaka_serial_syncSiPixelPhase2DigiToCluster = alpaka_serial_sync_SiPixelPhase2DigiToCluster()
