import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_SiPixelRawToClusterHIonPhase1 import alpaka_cuda_async_SiPixelRawToClusterHIonPhase1

alpaka_cuda_asyncSiPixelRawToClusterHIonPhase1 = alpaka_cuda_async_SiPixelRawToClusterHIonPhase1()
