import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_SiPixelPhase2DigiToCluster import alpaka_cuda_async_SiPixelPhase2DigiToCluster

alpaka_cuda_asyncSiPixelPhase2DigiToCluster = alpaka_cuda_async_SiPixelPhase2DigiToCluster()
