import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_SiPixelRawToClusterPhase1 import alpaka_cuda_async_SiPixelRawToClusterPhase1

alpaka_cuda_asyncSiPixelRawToClusterPhase1 = alpaka_cuda_async_SiPixelRawToClusterPhase1()
