import FWCore.ParameterSet.Config as cms

from .SeedCreatorFromRegionConsecutiveHitsEDProducer import SeedCreatorFromRegionConsecutiveHitsEDProducer

seedCreatorFromRegionConsecutiveHitsEDProducer = SeedCreatorFromRegionConsecutiveHitsEDProducer()
