import FWCore.ParameterSet.Config as cms

from .SeedCreatorFromRegionConsecutiveHitsTripletOnlyEDProducer import SeedCreatorFromRegionConsecutiveHitsTripletOnlyEDProducer

seedCreatorFromRegionConsecutiveHitsTripletOnlyEDProducer = SeedCreatorFromRegionConsecutiveHitsTripletOnlyEDProducer()
