import FWCore.ParameterSet.Config as cms

from .SeedGeneratorFromProtoTracksEDProducer import SeedGeneratorFromProtoTracksEDProducer

SeedGeneratorFromProtoTracksEDProducer = SeedGeneratorFromProtoTracksEDProducer()
