import FWCore.ParameterSet.Config as cms

from .SeedGeneratorFromL1TTracksEDProducer import SeedGeneratorFromL1TTracksEDProducer

seedGeneratorFromL1TTracksEDProducer = SeedGeneratorFromL1TTracksEDProducer()
