import FWCore.ParameterSet.Config as cms

from .FakeStateSeedCreatorFromRegionConsecutiveHitsEDProducer import FakeStateSeedCreatorFromRegionConsecutiveHitsEDProducer

seedCreatorFromRegionConsecutiveHitsSimpleEDProducer = FakeStateSeedCreatorFromRegionConsecutiveHitsEDProducer()
