import FWCore.ParameterSet.Config as cms

def MVATrainingNtuple(*args, **kwargs):
  mod = cms.EDAnalyzer('MVATrainingNtuple',
    inputTracks = cms.InputTag('generalTracks'),
    inputTagT = cms.InputTag('trackExtenderWithMTD'),
    inputTagV = cms.InputTag('offlinePrimaryVertices4D'),
    TPtoRecoTrackAssoc = cms.InputTag('trackingParticleRecoTrackAsssociation'),
    tp2SimAssociationMapTag = cms.InputTag('mtdSimLayerClusterToTPAssociation'),
    r2sAssociationMapTag = cms.InputTag('mtdRecoClusterToSimLayerClusterAssociation'),
    SimTag = cms.InputTag('mix', 'MergedTrackTruth'),
    offlineBS = cms.InputTag('offlineBeamSpot'),
    trackAssocSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackassoc'),
    recCluTagBTL = cms.InputTag('mtdClusters', 'FTLBarrel'),
    recCluTagETL = cms.InputTag('mtdClusters', 'FTLEndcap'),
    pathLengthSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackPathLength'),
    momentumSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackp'),
    tmtd = cms.InputTag('trackExtenderWithMTD', 'generalTracktmtd'),
    sigmaSrc = cms.InputTag('trackExtenderWithMTD', 'generalTracksigmatmtd'),
    t0Src = cms.InputTag('trackExtenderWithMTD', 'generalTrackt0'),
    sigmat0Src = cms.InputTag('trackExtenderWithMTD', 'generalTracksigmat0'),
    t0PID = cms.InputTag('tofPID', 't0'),
    sigmat0PID = cms.InputTag('tofPID', 'sigmat0'),
    t0SafePID = cms.InputTag('tofPID', 't0safe'),
    sigmat0SafePID = cms.InputTag('tofPID', 'sigmat0safe'),
    trackMVAQual = cms.InputTag('mtdTrackQualityMVA', 'mtdQualMVA'),
    tofPi = cms.InputTag('trackExtenderWithMTD', 'generalTrackTofPi'),
    tofK = cms.InputTag('trackExtenderWithMTD', 'generalTrackTofK'),
    tofP = cms.InputTag('trackExtenderWithMTD', 'generalTrackTofP'),
    probPi = cms.InputTag('tofPID', 'probPi'),
    probK = cms.InputTag('tofPID', 'probK'),
    probP = cms.InputTag('tofPID', 'probP'),
    sigmatofpiSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackSigmaTofPi'),
    sigmatofkSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackSigmaTofK'),
    sigmatofpSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackSigmaTofP'),
    btlMatchChi2Src = cms.InputTag('trackExtenderWithMTD', 'btlMatchChi2'),
    btlMatchTimeChi2Src = cms.InputTag('trackExtenderWithMTD', 'btlMatchTimeChi2'),
    etlMatchChi2Src = cms.InputTag('trackExtenderWithMTD', 'etlMatchChi2'),
    etlMatchTimeChi2Src = cms.InputTag('trackExtenderWithMTD', 'etlMatchTimeChi2'),
    npixBarrelSrc = cms.InputTag('trackExtenderWithMTD', 'npixBarrel'),
    npixEndcapSrc = cms.InputTag('trackExtenderWithMTD', 'npixEndcap'),
    outermostHitPositionSrc = cms.InputTag('trackExtenderWithMTD', 'generalTrackOutermostHitPosition'),
    fileName = cms.untracked.string('file.root'),
    ntupleforBDT = cms.bool(True),
    ntupleforGNN = cms.bool(False),
    TkFilterParameters = cms.PSet(
      maxNormalizedChi2 = cms.double(10),
      minPt = cms.double(0),
      algorithm = cms.string('filter'),
      maxEta = cms.double(2.4),
      maxD0Significance = cms.double(4),
      maxD0Error = cms.double(1),
      maxDzError = cms.double(1),
      trackQuality = cms.string('any'),
      minPixelLayersWithHits = cms.int32(2),
      minSiliconLayersWithHits = cms.int32(5),
      minValidStripHits = cms.int32(0),
      numTracksThreshold = cms.int32(0),
      maxNumTracksThreshold = cms.int32(2147483647),
      minPtTight = cms.double(0)
    ),
    mightGet = cms.optional.untracked.vstring
  )
  for a in args:
    mod.update_(a)
  mod.update_(kwargs)
  return mod
