import FWCore.ParameterSet.Config as cms

from .VertexAssociatorByPositionAndTracksProducerCPC import VertexAssociatorByPositionAndTracksProducerCPC

vertexAssociatorByPositionAndTracksProducerCPC = VertexAssociatorByPositionAndTracksProducerCPC()
