import FWCore.ParameterSet.Config as cms

from .VertexAssociatorByPositionAndTracksProducer import VertexAssociatorByPositionAndTracksProducer

VertexAssociatorByPositionAndTracks = VertexAssociatorByPositionAndTracksProducer()
