import FWCore.ParameterSet.Config as cms

from .VertexAssociatorByPositionAndTracksProducer import VertexAssociatorByPositionAndTracksProducer

vertexAssociatorByPositionAndTracksProducer = VertexAssociatorByPositionAndTracksProducer()
