import FWCore.ParameterSet.Config as cms

from .VertexCompositePtrCandidateAssociatorEDProducer import VertexCompositePtrCandidateAssociatorEDProducer

vertexCompositePtrCandidateAssociatorEDProducer = VertexCompositePtrCandidateAssociatorEDProducer()
