import FWCore.ParameterSet.Config as cms

from .VertexAssociatorByTracksProducer_std_vector_reco_Vertex__ import VertexAssociatorByTracksProducer_std_vector_reco_Vertex__

VertexAssociatorByTracks = VertexAssociatorByTracksProducer_std_vector_reco_Vertex__()
