import FWCore.ParameterSet.Config as cms

from .BeamSpotOnlineFromOfflineConverter import BeamSpotOnlineFromOfflineConverter

beamSpotOnlineFromOfflineConverter = BeamSpotOnlineFromOfflineConverter()
