import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_torchtest_MaskedNet import alpaka_rocm_async_torchtest_MaskedNet

alpaka_rocm_asynctorchtestMaskedNet = alpaka_rocm_async_torchtest_MaskedNet()
