import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_torchtest_MultiHeadNet import alpaka_rocm_async_torchtest_MultiHeadNet

alpaka_rocm_asynctorchtestMultiHeadNet = alpaka_rocm_async_torchtest_MultiHeadNet()
