import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_torchtest_MaskedNet import alpaka_cuda_async_torchtest_MaskedNet

alpaka_cuda_asynctorchtestMaskedNet = alpaka_cuda_async_torchtest_MaskedNet()
