import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_torchtest_MultiHeadNet import alpaka_cuda_async_torchtest_MultiHeadNet

alpaka_cuda_asynctorchtestMultiHeadNet = alpaka_cuda_async_torchtest_MultiHeadNet()
