import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_torchtest_SimpleNet import alpaka_rocm_async_torchtest_SimpleNet

alpaka_rocm_asynctorchtestSimpleNet = alpaka_rocm_async_torchtest_SimpleNet()
