import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_torchtest_SimpleNetMiniBatch import alpaka_cuda_async_torchtest_SimpleNetMiniBatch

alpaka_cuda_asynctorchtestSimpleNetMiniBatch = alpaka_cuda_async_torchtest_SimpleNetMiniBatch()
