import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationByHPSSelection import PFRecoTauDiscriminationByHPSSelection

hpsSelectionDiscriminator = PFRecoTauDiscriminationByHPSSelection()
