import FWCore.ParameterSet.Config as cms

from .PATTauDiscriminationAgainstElectronDeadECAL import PATTauDiscriminationAgainstElectronDeadECAL

patTauDiscriminationAgainstElectronDeadECAL = PATTauDiscriminationAgainstElectronDeadECAL()
