import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationByIsolation import PFRecoTauDiscriminationByIsolation

pfRecoTauDiscriminationByIsolation = PFRecoTauDiscriminationByIsolation()
