import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationAgainstElectronDeadECAL import PFRecoTauDiscriminationAgainstElectronDeadECAL

pfRecoTauDiscriminationAgainstElectronDeadECAL = PFRecoTauDiscriminationAgainstElectronDeadECAL()
