import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationAgainstMuon import PFRecoTauDiscriminationAgainstMuon

pfRecoTauDiscriminationAgainstMuon = PFRecoTauDiscriminationAgainstMuon()
