import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationAgainstCaloMuon import PFRecoTauDiscriminationAgainstCaloMuon

pfRecoTauDiscriminationAgainstCaloMuon = PFRecoTauDiscriminationAgainstCaloMuon()
