import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationByIsolationContainer import PFRecoTauDiscriminationByIsolationContainer

pfRecoTauDiscriminationByIsolationContainer = PFRecoTauDiscriminationByIsolationContainer()
