import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationAgainstMuonSimple import PFRecoTauDiscriminationAgainstMuonSimple

pfRecoTauDiscriminationAgainstMuonSimple = PFRecoTauDiscriminationAgainstMuonSimple()
