import FWCore.ParameterSet.Config as cms

pfRecoTauDiscriminationAgainstElectronMVA5 = cms.EDProducer('PFRecoTauDiscriminationAgainstElectronMVA5',
  minMVANoEleMatchWOgWOgsfBL = cms.double(0),
  PFTauProducer = cms.InputTag('pfTauProducer'),
  mvaName_woGwoGSF_EC = cms.string('gbr_woGwoGSF_EC'),
  minMVANoEleMatchWgWOgsfBL = cms.double(0),
  mvaName_woGwGSF_EC = cms.string('gbr_woGwGSF_EC'),
  mvaName_wGwGSF_EC = cms.string('gbr_wGwGSF_EC'),
  minMVAWgWgsfBL = cms.double(0),
  minMVAWgWOgsfBL = cms.double(0),
  minMVANoEleMatchWgWgsfBL = cms.double(0),
  minMVAWOgWgsfEC = cms.double(0),
  mvaName_wGwGSF_BL = cms.string('gbr_wGwGSF_BL'),
  mvaName_woGwGSF_BL = cms.string('gbr_woGwGSF_BL'),
  returnMVA = cms.bool(True),
  minMVANoEleMatchWgWOgsfEC = cms.double(0),
  loadMVAfromDB = cms.bool(True),
  Prediscriminants = cms.PSet(
    BooleanOperator = cms.string('and'),
    leadTrack = cms.PSet()
  ),
  mvaName_wGwoGSF_EC = cms.string('gbr_wGwoGSF_EC'),
  mvaName_NoEleMatch_woGwoGSF_BL = cms.string('gbr_NoEleMatch_woGwoGSF_BL'),
  minMVAWOgWOgsfEC = cms.double(0),
  mvaName_woGwoGSF_BL = cms.string('gbr_woGwoGSF_BL'),
  mvaName_wGwoGSF_BL = cms.string('gbr_wGwoGSF_BL'),
  minMVANoEleMatchWOgWOgsfEC = cms.double(0),
  mvaName_NoEleMatch_woGwGSF_BL = cms.string('gbr_NoEleMatch_woGwGSF_BL'),
  minMVANoEleMatchWgWgsfEC = cms.double(0),
  minMVAWOgWgsfBL = cms.double(0),
  minMVANoEleMatchWOgWgsfEC = cms.double(0),
  minMVAWgWOgsfEC = cms.double(0),
  mvaName_NoEleMatch_wGwGSF_EC = cms.string('gbr_NoEleMatch_wGwGSF_EC'),
  minMVAWgWgsfEC = cms.double(0),
  verbosity = cms.int32(0),
  minMVANoEleMatchWOgWgsfBL = cms.double(0),
  mvaName_NoEleMatch_wGwoGSF_EC = cms.string('gbr_NoEleMatch_wGwoGSF_EC'),
  method = cms.string('BDTG'),
  mvaName_NoEleMatch_wGwGSF_BL = cms.string('gbr_NoEleMatch_wGwGSF_BL'),
  mvaName_NoEleMatch_wGwoGSF_BL = cms.string('gbr_NoEleMatch_wGwoGSF_BL'),
  srcGsfElectrons = cms.InputTag('gedGsfElectrons'),
  minMVAWOgWOgsfBL = cms.double(0),
  mvaName_NoEleMatch_woGwoGSF_EC = cms.string('gbr_NoEleMatch_woGwoGSF_EC'),
  mvaName_NoEleMatch_woGwGSF_EC = cms.string('gbr_NoEleMatch_woGwGSF_EC')
)
