import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationAgainstElectron import PFRecoTauDiscriminationAgainstElectron

pfRecoTauDiscriminationAgainstElectron = PFRecoTauDiscriminationAgainstElectron()
