import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationAgainstMuonMVA import PFRecoTauDiscriminationAgainstMuonMVA

pfRecoTauDiscriminationAgainstMuonMVA = PFRecoTauDiscriminationAgainstMuonMVA()
