import FWCore.ParameterSet.Config as cms

from .PFRecoTauDiscriminationByLeadingObjectPtCut import PFRecoTauDiscriminationByLeadingObjectPtCut

pfRecoTauDiscriminationByLeadingObjectPtCut = PFRecoTauDiscriminationByLeadingObjectPtCut()
