import FWCore.ParameterSet.Config as cms

from .PFTauDiscriminatorLogicalAndProducer import PFTauDiscriminatorLogicalAndProducer

PFTauDiscriminatorLogicalAndProducer = PFTauDiscriminatorLogicalAndProducer()
