import FWCore.ParameterSet.Config as cms

from .RecoTauDiscriminantCutMultiplexer import RecoTauDiscriminantCutMultiplexer

recoTauDiscriminantCutMultiplexerDefault = RecoTauDiscriminantCutMultiplexer()
