import FWCore.ParameterSet.Config as cms

from .CandidateJetBProbabilityESProducer import CandidateJetBProbabilityESProducer

candidateJetBProbabilityESProducer = CandidateJetBProbabilityESProducer()
