import FWCore.ParameterSet.Config as cms

from .CandidateNegativeTrackCountingESProducer import CandidateNegativeTrackCountingESProducer

candidateNegativeTrackCountingESProducer = CandidateNegativeTrackCountingESProducer()
