import FWCore.ParameterSet.Config as cms

from .ConcreteChargedRefCandidateProducer import ConcreteChargedRefCandidateProducer

concreteChargedRefCandidateProducer = ConcreteChargedRefCandidateProducer()
