import FWCore.ParameterSet.Config as cms

from .ConcreteStandAloneMuonCandidateProducer import ConcreteStandAloneMuonCandidateProducer

concreteStandAloneMuonCandidateProducer = ConcreteStandAloneMuonCandidateProducer()
