import FWCore.ParameterSet.Config as cms

from .EtaPtMinPixelMatchGsfElectronFullCloneSelector import EtaPtMinPixelMatchGsfElectronFullCloneSelector

etaPtMinPixelMatchGsfElectronFullCloneSelector = EtaPtMinPixelMatchGsfElectronFullCloneSelector()
