import FWCore.ParameterSet.Config as cms

from .EtaPtMinGsfElectronFullCloneSelector import EtaPtMinGsfElectronFullCloneSelector

etaPtMinGsfElectronFullCloneSelector = EtaPtMinGsfElectronFullCloneSelector()
