import FWCore.ParameterSet.Config as cms

from .EtaPtMinPixelMatchGsfElectronSelector import EtaPtMinPixelMatchGsfElectronSelector

etaPtMinPixelMatchGsfElectronSelector = EtaPtMinPixelMatchGsfElectronSelector()
