import FWCore.ParameterSet.Config as cms

from .GenJetPackedConstituentPtrSelector import GenJetPackedConstituentPtrSelector

genJetPackedConstituentPtrSelector = GenJetPackedConstituentPtrSelector()
