import FWCore.ParameterSet.Config as cms

from .RecoChargedRefCandidateToTrackRefProducer import RecoChargedRefCandidateToTrackRefProducer

recoChargedRefCandidateToTrackRefProducer = RecoChargedRefCandidateToTrackRefProducer()
