import FWCore.ParameterSet.Config as cms

from .RecoChargedRefCandidatePrimaryVertexSorter import RecoChargedRefCandidatePrimaryVertexSorter

sortedPrimaryVertices = RecoChargedRefCandidatePrimaryVertexSorter()
