import FWCore.ParameterSet.Config as cms

from .TrackingParticleConversionRefSelector import TrackingParticleConversionRefSelector

trackingParticleConversionRefSelectorDefault = TrackingParticleConversionRefSelector()
