import FWCore.ParameterSet.Config as cms

from .VertexCompositeCandidateCollectionSelector import VertexCompositeCandidateCollectionSelector

VertexCompositeCandidateCollectionSelector = VertexCompositeCandidateCollectionSelector()
