import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_HcalMahiPulseOffsetsESProducer import alpaka_serial_sync_HcalMahiPulseOffsetsESProducer

alpaka_serial_syncHcalMahiPulseOffsetsESProducer = alpaka_serial_sync_HcalMahiPulseOffsetsESProducer()
