import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_HcalSiPMCharacteristicsESProducer import alpaka_rocm_async_HcalSiPMCharacteristicsESProducer

alpaka_rocm_asyncHcalSiPMCharacteristicsESProducer = alpaka_rocm_async_HcalSiPMCharacteristicsESProducer()
