import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_HcalMahiConditionsESProducer import alpaka_serial_sync_HcalMahiConditionsESProducer

alpaka_serial_syncHcalMahiConditionsESProducer = alpaka_serial_sync_HcalMahiConditionsESProducer()
