import FWCore.ParameterSet.Config as cms

from .HcalConvertedPedestalWidthsGPUESProducer import HcalConvertedPedestalWidthsGPUESProducer

hcalConvertedPedestalWidthsGPUESProducer = HcalConvertedPedestalWidthsGPUESProducer()
