import FWCore.ParameterSet.Config as cms

from .HcalConvertedPedestalsGPUESProducer import HcalConvertedPedestalsGPUESProducer

hcalConvertedPedestalsGPUESProducer = HcalConvertedPedestalsGPUESProducer()
