import FWCore.ParameterSet.Config as cms

from .HcalConvertedEffectivePedestalWidthsGPUESProducer import HcalConvertedEffectivePedestalWidthsGPUESProducer

hcalConvertedEffectivePedestalWidthsGPUESProducer = HcalConvertedEffectivePedestalWidthsGPUESProducer()
