import FWCore.ParameterSet.Config as cms

from .HcalRecoParamsWithPulseShapesGPUESProducer import HcalRecoParamsWithPulseShapesGPUESProducer

hcalRecoParamsWithPulseShapesGPUESProducer = HcalRecoParamsWithPulseShapesGPUESProducer()
