import FWCore.ParameterSet.Config as cms

from .HcalConvertedEffectivePedestalsGPUESProducer import HcalConvertedEffectivePedestalsGPUESProducer

hcalConvertedEffectivePedestalsGPUESProducer = HcalConvertedEffectivePedestalsGPUESProducer()
