import FWCore.ParameterSet.Config as cms

from .HcalSiPMCharacteristicsGPUESProducer import HcalSiPMCharacteristicsGPUESProducer

hcalSiPMCharacteristicsGPUESProducer = HcalSiPMCharacteristicsGPUESProducer()
