import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_EcalElectronicsMappingHostESProducer import alpaka_cuda_async_EcalElectronicsMappingHostESProducer

alpaka_cuda_asyncEcalElectronicsMappingHostESProducer = alpaka_cuda_async_EcalElectronicsMappingHostESProducer()
