import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_EcalElectronicsMappingHostESProducer import alpaka_serial_sync_EcalElectronicsMappingHostESProducer

alpaka_serial_syncEcalElectronicsMappingHostESProducer = alpaka_serial_sync_EcalElectronicsMappingHostESProducer()
