import FWCore.ParameterSet.Config as cms

from .EcalElectronicsMappingGPUESProducer import EcalElectronicsMappingGPUESProducer

ecalElectronicsMappingGPUESProducer = EcalElectronicsMappingGPUESProducer()
