import FWCore.ParameterSet.Config as cms

from .SkippingLayerCosmicNavigationSchoolESProducer import SkippingLayerCosmicNavigationSchoolESProducer

skippingLayerCosmicNavigationSchoolESProducer = SkippingLayerCosmicNavigationSchoolESProducer()
