import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_SiPixelRecHitAlpakaPhase2 import alpaka_rocm_async_SiPixelRecHitAlpakaPhase2

alpaka_rocm_asyncSiPixelRecHitAlpakaPhase2 = alpaka_rocm_async_SiPixelRecHitAlpakaPhase2()
