import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_SiPixelRecHitAlpakaPhase2 import alpaka_serial_sync_SiPixelRecHitAlpakaPhase2

alpaka_serial_syncSiPixelRecHitAlpakaPhase2 = alpaka_serial_sync_SiPixelRecHitAlpakaPhase2()
