import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_SiPixelRecHitAlpakaHIonPhase1 import alpaka_serial_sync_SiPixelRecHitAlpakaHIonPhase1

alpaka_serial_syncSiPixelRecHitAlpakaHIonPhase1 = alpaka_serial_sync_SiPixelRecHitAlpakaHIonPhase1()
