import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_PixelCPEFastParamsESProducerAlpakaPhase2 import alpaka_serial_sync_PixelCPEFastParamsESProducerAlpakaPhase2

alpaka_serial_syncPixelCPEFastParamsESProducerAlpakaPhase2 = alpaka_serial_sync_PixelCPEFastParamsESProducerAlpakaPhase2()
