import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_PixelCPEFastParamsESProducerAlpakaHIonPhase1 import alpaka_rocm_async_PixelCPEFastParamsESProducerAlpakaHIonPhase1

alpaka_rocm_asyncPixelCPEFastParamsESProducerAlpakaHIonPhase1 = alpaka_rocm_async_PixelCPEFastParamsESProducerAlpakaHIonPhase1()
