import FWCore.ParameterSet.Config as cms

from .alpaka_cuda_async_PixelCPEFastParamsESProducerAlpakaPhase1 import alpaka_cuda_async_PixelCPEFastParamsESProducerAlpakaPhase1

alpaka_cuda_asyncPixelCPEFastParamsESProducerAlpakaPhase1 = alpaka_cuda_async_PixelCPEFastParamsESProducerAlpakaPhase1()
