import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_PixelCPEFastParamsESProducerAlpakaPhase2 import alpaka_rocm_async_PixelCPEFastParamsESProducerAlpakaPhase2

alpaka_rocm_asyncPixelCPEFastParamsESProducerAlpakaPhase2 = alpaka_rocm_async_PixelCPEFastParamsESProducerAlpakaPhase2()
