import FWCore.ParameterSet.Config as cms

from .SiPixelRecHitSoAFromLegacyHIonPhase1 import SiPixelRecHitSoAFromLegacyHIonPhase1

siPixelRecHitSoAFromLegacyHIonPhase1 = SiPixelRecHitSoAFromLegacyHIonPhase1()
