import FWCore.ParameterSet.Config as cms

from .MultipleScatteringParametrisationMakerESProducer import MultipleScatteringParametrisationMakerESProducer

multipleScatteringParametrisationMakerESProducer = MultipleScatteringParametrisationMakerESProducer()
