import FWCore.ParameterSet.Config as cms

from .CTPPSInterpolatedOpticalFunctionsESSource import CTPPSInterpolatedOpticalFunctionsESSource

ctppsInterpolatedOpticalFunctionsESSourceDefault = CTPPSInterpolatedOpticalFunctionsESSource()
