import FWCore.ParameterSet.Config as cms

from .CTPPSBeamParametersFromLHCInfoESSource import CTPPSBeamParametersFromLHCInfoESSource

ctppsBeamParametersFromLHCInfoESSourceDefault = CTPPSBeamParametersFromLHCInfoESSource()
