import FWCore.ParameterSet.Config as cms

from .RPCInverseTwinMuxLinkMapESProducer import RPCInverseTwinMuxLinkMapESProducer

RPCInverseTwinMuxLinkMapESProducer = RPCInverseTwinMuxLinkMapESProducer()
