import FWCore.ParameterSet.Config as cms

from .ElectronHcalPFClusterIsolationProducer import ElectronHcalPFClusterIsolationProducer

egammaHcalPFClusterIsolationProducerRecoGsfElectron = ElectronHcalPFClusterIsolationProducer()
