import FWCore.ParameterSet.Config as cms

from .PhotonHcalPFClusterIsolationProducer import PhotonHcalPFClusterIsolationProducer

egammaHcalPFClusterIsolationProducerRecoPhoton = PhotonHcalPFClusterIsolationProducer()
