import FWCore.ParameterSet.Config as cms

from .ElectronEcalPFClusterIsolationProducer import ElectronEcalPFClusterIsolationProducer

egammaEcalPFClusterIsolationProducerRecoGsfElectron = ElectronEcalPFClusterIsolationProducer()
