import FWCore.ParameterSet.Config as cms

from .PhotonEcalPFClusterIsolationProducer import PhotonEcalPFClusterIsolationProducer

egammaEcalPFClusterIsolationProducerRecoPhoton = PhotonEcalPFClusterIsolationProducer()
