import FWCore.ParameterSet.Config as cms

from .EgammaIsoHcalDetIdCollectionProducer import EgammaIsoHcalDetIdCollectionProducer

interestingGedEgammaIsoHCALDetId = EgammaIsoHcalDetIdCollectionProducer()
