import FWCore.ParameterSet.Config as cms

from .AlignmentCSCBeamHaloSelectorModule import AlignmentCSCBeamHaloSelectorModule

alignmentCSCBeamHaloSelectorModule = AlignmentCSCBeamHaloSelectorModule()
