import FWCore.ParameterSet.Config as cms

from .AlignmentTrackFromVertexSelectorModule import AlignmentTrackFromVertexSelectorModule

alignmentTrackFromVertexSelectorModule = AlignmentTrackFromVertexSelectorModule()
