import FWCore.ParameterSet.Config as cms

from .AlignmentTrackFromVertexCompositeCandidateSelectorModule import AlignmentTrackFromVertexCompositeCandidateSelectorModule

alignmentTrackFromVertexCompositeCandidateSelectorModule = AlignmentTrackFromVertexCompositeCandidateSelectorModule()
