import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_EcalRecHitConditionsESProducer import alpaka_rocm_async_EcalRecHitConditionsESProducer

alpaka_rocm_asyncEcalRecHitConditionsESProducer = alpaka_rocm_async_EcalRecHitConditionsESProducer()
