import FWCore.ParameterSet.Config as cms

from .alpaka_serial_sync_EcalRecHitParametersESProducer import alpaka_serial_sync_EcalRecHitParametersESProducer

alpaka_serial_syncEcalRecHitParametersESProducer = alpaka_serial_sync_EcalRecHitParametersESProducer()
