import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_EcalUncalibRecHitPhase2WeightsProducerPortable import alpaka_rocm_async_EcalUncalibRecHitPhase2WeightsProducerPortable

alpaka_rocm_asyncEcalUncalibRecHitPhase2WeightsProducerPortable = alpaka_rocm_async_EcalUncalibRecHitPhase2WeightsProducerPortable()
