import FWCore.ParameterSet.Config as cms

from .EcalRechitADCToGeVConstantGPUESProducer import EcalRechitADCToGeVConstantGPUESProducer

ecalRechitADCToGeVConstantGPUESProducer = EcalRechitADCToGeVConstantGPUESProducer()
