import FWCore.ParameterSet.Config as cms

from .EcalSamplesCorrelationGPUESProducer import EcalSamplesCorrelationGPUESProducer

ecalSamplesCorrelationGPUESProducer = EcalSamplesCorrelationGPUESProducer()
