import FWCore.ParameterSet.Config as cms

from .EcalLaserAPDPNRatiosRefGPUESProducer import EcalLaserAPDPNRatiosRefGPUESProducer

ecalLaserAPDPNRatiosRefGPUESProducer = EcalLaserAPDPNRatiosRefGPUESProducer()
