import FWCore.ParameterSet.Config as cms

from .EcalRecHitConditionsESProducer_alpaka import EcalRecHitConditionsESProducer_alpaka

ecalRecHitConditionsESProducer = EcalRecHitConditionsESProducer_alpaka()
