import FWCore.ParameterSet.Config as cms

from .EcalLinearCorrectionsGPUESProducer import EcalLinearCorrectionsGPUESProducer

ecalLinearCorrectionsGPUESProducer = EcalLinearCorrectionsGPUESProducer()
