import FWCore.ParameterSet.Config as cms

from .EcalTimeBiasCorrectionsGPUESProducer import EcalTimeBiasCorrectionsGPUESProducer

ecalTimeBiasCorrectionsGPUESProducer = EcalTimeBiasCorrectionsGPUESProducer()
