import FWCore.ParameterSet.Config as cms

from .EcalRechitChannelStatusGPUESProducer import EcalRechitChannelStatusGPUESProducer

ecalRechitChannelStatusGPUESProducer = EcalRechitChannelStatusGPUESProducer()
