import FWCore.ParameterSet.Config as cms

from .EcalMultifitParametersGPUESProducer import EcalMultifitParametersGPUESProducer

ecalMultifitParametersGPUESProducer = EcalMultifitParametersGPUESProducer()
