import FWCore.ParameterSet.Config as cms

from .EcalIntercalibConstantsGPUESProducer import EcalIntercalibConstantsGPUESProducer

ecalIntercalibConstantsGPUESProducer = EcalIntercalibConstantsGPUESProducer()
