import FWCore.ParameterSet.Config as cms

from .EcalTimeCalibConstantsGPUESProducer import EcalTimeCalibConstantsGPUESProducer

ecalTimeCalibConstantsGPUESProducer = EcalTimeCalibConstantsGPUESProducer()
