import FWCore.ParameterSet.Config as cms

from .ScoutingEGammaCollectionMonitoring import ScoutingEGammaCollectionMonitoring

scoutingEGammaCollectionMonitoring = ScoutingEGammaCollectionMonitoring()
