import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_hgcalrechit_HGCalCalibrationESProducer import alpaka_rocm_async_hgcalrechit_HGCalCalibrationESProducer

alpaka_rocm_asynchgcalrechitHGCalCalibrationESProducer = alpaka_rocm_async_hgcalrechit_HGCalCalibrationESProducer()
