import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_CAHitNtupletAlpakaHIonPhase1 import alpaka_rocm_async_CAHitNtupletAlpakaHIonPhase1

alpaka_rocm_asyncCAHitNtupletAlpakaHIonPhase1 = alpaka_rocm_async_CAHitNtupletAlpakaHIonPhase1()
