import FWCore.ParameterSet.Config as cms

from .alpaka_rocm_async_CAHitNtupletAlpakaPhase2 import alpaka_rocm_async_CAHitNtupletAlpakaPhase2

alpaka_rocm_asyncCAHitNtupletAlpakaPhase2 = alpaka_rocm_async_CAHitNtupletAlpakaPhase2()
