import FWCore.ParameterSet.Config as cms

from .FastPrimaryVertexWithWeightsProducer import FastPrimaryVertexWithWeightsProducer

fastPrimaryVertexWithWeightsProducer = FastPrimaryVertexWithWeightsProducer()
