import FWCore.ParameterSet.Config as cms

from .EcalSCDynamicDPhiParametersESProducer import EcalSCDynamicDPhiParametersESProducer

ecalSCDynamicDPhiParametersESProducer = EcalSCDynamicDPhiParametersESProducer()
