import FWCore.ParameterSet.Config as cms

from .EcalMustacheSCParametersESProducer import EcalMustacheSCParametersESProducer

ecalMustacheSCParametersESProducer = EcalMustacheSCParametersESProducer()
