import FWCore.ParameterSet.Config as cms

from .SelectedElectronFEDListProducerGsf import SelectedElectronFEDListProducerGsf

selectedElectronFEDListProducerRecoElectronRecoRecoEcalCandidate = SelectedElectronFEDListProducerGsf()
