import FWCore.ParameterSet.Config as cms

from .Phase2TrackerClusterizerValidationTGraph import Phase2TrackerClusterizerValidationTGraph

phase2TrackerClusterizerValidationTGraph = Phase2TrackerClusterizerValidationTGraph()
