import FWCore.ParameterSet.Config as cms

def BarrelValidator(*args, **kwargs):
  mod = cms.EDProducer('BarrelValidator',
    ptMinCP = cms.double(0.5),
    ptMaxCP = cms.double(300),
    minRapidityCP = cms.double(-3.1),
    maxRapidityCP = cms.double(3.1),
    lipCP = cms.double(30),
    tipCP = cms.double(60),
    chargedOnlyCP = cms.bool(False),
    stableOnlyCP = cms.bool(False),
    notConvertedOnlyCP = cms.bool(True),
    pdgIdCP = cms.vint32(
      11,
      -11,
      13,
      -13,
      22,
      111,
      211,
      -211,
      321,
      -321,
      311,
      130,
      310
    ),
    signalOnlyCP = cms.bool(True),
    intimeOnlyCP = cms.bool(True),
    minHitCP = cms.int32(0),
    maxSimClustersCP = cms.int32(-1),
    histoProducerAlgoBlock = cms.PSet(
      minEta = cms.double(-4.5),
      maxEta = cms.double(4.5),
      nintEta = cms.int32(100),
      useFabsEta = cms.bool(False),
      minEne = cms.double(0),
      maxEne = cms.double(500),
      nintEne = cms.int32(250),
      minPt = cms.double(0),
      maxPt = cms.double(100),
      nintPt = cms.int32(100),
      minPhi = cms.double(-3.2),
      maxPhi = cms.double(3.2),
      nintPhi = cms.int32(80),
      minMixedHitsSimCluster = cms.double(0),
      maxMixedHitsSimCluster = cms.double(800),
      nintMixedHitsSimCluster = cms.int32(100),
      minMixedHitsCluster = cms.double(0),
      maxMixedHitsCluster = cms.double(800),
      nintMixedHitsCluster = cms.int32(100),
      minEneCl = cms.double(0),
      maxEneCl = cms.double(110),
      nintEneCl = cms.int32(110),
      minLongDepBary = cms.double(0),
      maxLongDepBary = cms.double(110),
      nintLongDepBary = cms.int32(110),
      minZpos = cms.double(-550),
      maxZpos = cms.double(550),
      nintZpos = cms.int32(1100),
      minTotNsimClsperlay = cms.double(0),
      maxTotNsimClsperlay = cms.double(50),
      nintTotNsimClsperlay = cms.int32(50),
      minTotNClsperlay = cms.double(0),
      maxTotNClsperlay = cms.double(1000),
      nintTotNClsperlay = cms.int32(50),
      minEneClperlay = cms.double(0),
      maxEneClperlay = cms.double(1000),
      nintEneClperlay = cms.int32(110),
      minScore = cms.double(0),
      maxScore = cms.double(1.02),
      nintScore = cms.int32(51),
      minSharedEneFrac = cms.double(0),
      maxSharedEneFrac = cms.double(1.02),
      nintSharedEneFrac = cms.int32(51),
      minTSTSharedEneFracEfficiency = cms.double(0.5),
      minTSTSharedEneFrac = cms.double(0),
      maxTSTSharedEneFrac = cms.double(1.01),
      nintTSTSharedEneFrac = cms.int32(101),
      minTotNTSTs = cms.double(0),
      maxTotNTSTs = cms.double(50),
      nintTotNTSTs = cms.int32(50),
      minTotNClsinTSTs = cms.double(0),
      maxTotNClsinTSTs = cms.double(400),
      nintTotNClsinTSTs = cms.int32(100),
      minTotNClsinTSTsperlayer = cms.double(0),
      maxTotNClsinTSTsperlayer = cms.double(50),
      nintTotNClsinTSTsperlayer = cms.int32(50),
      minMplofLCs = cms.double(0),
      maxMplofLCs = cms.double(20),
      nintMplofLCs = cms.int32(20),
      minSizeCLsinTSTs = cms.double(0),
      maxSizeCLsinTSTs = cms.double(50),
      nintSizeCLsinTSTs = cms.int32(50),
      minClEnepermultiplicity = cms.double(0),
      maxClEnepermultiplicity = cms.double(10),
      nintClEnepermultiplicity = cms.int32(10),
      minX = cms.double(-300),
      maxX = cms.double(300),
      nintX = cms.int32(100),
      minY = cms.double(-300),
      maxY = cms.double(300),
      nintY = cms.int32(100),
      minZ = cms.double(-550),
      maxZ = cms.double(550),
      nintZ = cms.int32(1100)
    ),
    hgcal_hits = cms.VInputTag(
      'HGCalRecHit:HGCEERecHits',
      'HGCalRecHit:HGCHEFRecHits',
      'HGCalRecHit:HGCHEBRecHits'
    ),
    barrel_hits = cms.VInputTag(
      'particleFlowRecHitECAL',
      'particleFlowRecHitHBHE'
    ),
    label_lcl = cms.InputTag('hgcalMergeLayerClusters'),
    label_tst = cms.VInputTag(
      'ticlTrackstersCLUE3DHigh',
      'ticlTrackstersMerge',
      'ticlSimTracksters:fromCPs',
      'ticlSimTracksters'
    ),
    label_simTS = cms.InputTag('ticlSimTracksters'),
    label_simTSFromCP = cms.InputTag('ticlSimTracksters', 'fromCPs'),
    associator = cms.untracked.VInputTag('barrelLayerClusterCaloParticleAssociation'),
    associatorSim = cms.untracked.VInputTag('barrelLayerClusterSimClusterAssociation'),
    SaveGeneralInfo = cms.untracked.bool(True),
    doCaloParticlePlots = cms.untracked.bool(True),
    doCaloParticleSelection = cms.untracked.bool(True),
    doSimClustersPlots = cms.untracked.bool(True),
    label_SimClusters = cms.InputTag('SimClusters'),
    label_SimClustersLevel = cms.InputTag('ClusterLevel'),
    doLayerClustersPlots = cms.untracked.bool(True),
    label_layerClusterPlots = cms.InputTag('hgcalMergeLayerClusters'),
    label_LCToCPLinking = cms.InputTag('LCToCP_association'),
    simClustersToCaloParticlesMap = cms.InputTag('SimClusterToCaloParticleAssociation', 'simClusterToCaloParticleMap'),
    label_cp_effic = cms.InputTag('mix', 'MergedCaloTruth'),
    label_cp_fake = cms.InputTag('mix', 'MergedCaloTruth'),
    label_scl = cms.InputTag('mix', 'MergedCaloTruth'),
    simVertices = cms.InputTag('g4SimHits'),
    totallayers_to_monitor = cms.int32(5),
    dirName = cms.string('BarrelCalorimeters/BarrelValidator/'),
    mightGet = cms.optional.untracked.vstring
  )
  for a in args:
    mod.update_(a)
  mod.update_(kwargs)
  return mod
