import FWCore.ParameterSet.Config as cms

from .TracksterSuperclusteringValidCandidateMaskProducer import TracksterSuperclusteringValidCandidateMaskProducer

tracksterSuperclusteringValidCandidateMaskProducer = TracksterSuperclusteringValidCandidateMaskProducer()
