import FWCore.ParameterSet.Config as cms

from .L1TRegionalMuonCandComparisonResultFilter import L1TRegionalMuonCandComparisonResultFilter

l1TRegionalMuonCandComparisonResultFilter = L1TRegionalMuonCandComparisonResultFilter()
