import FWCore.ParameterSet.Config as cms

from .PixelTrackProducerFromSoAAlpakaPhase2 import PixelTrackProducerFromSoAAlpakaPhase2

pixelTrackProducerFromSoAAlpakaPhase2 = PixelTrackProducerFromSoAAlpakaPhase2()
