import FWCore.ParameterSet.Config as cms

from .PixelFitterByHelixProjectionsProducer import PixelFitterByHelixProjectionsProducer

pixelFitterByHelixProjectionsDefault = PixelFitterByHelixProjectionsProducer()
