import FWCore.ParameterSet.Config as cms

from .PixelTrackCleanerBySharedHitsESProducer import PixelTrackCleanerBySharedHitsESProducer

pixelTrackCleanerBySharedHits = PixelTrackCleanerBySharedHitsESProducer()
