import FWCore.ParameterSet.Config as cms

from .PixelTrackFilterByKinematicsProducer import PixelTrackFilterByKinematicsProducer

pixelTrackFilterByKinematics = PixelTrackFilterByKinematicsProducer()
