import FWCore.ParameterSet.Config as cms

from .PixelFitterByConformalMappingAndLineProducer import PixelFitterByConformalMappingAndLineProducer

pixelFitterByConformalMappingAndLine = PixelFitterByConformalMappingAndLineProducer()
