import FWCore.ParameterSet.Config as cms

metPlusTrackMonitoring = cms.EDAnalyzer('METplusTrackMonitor',
  FolderName = cms.string('HLT/MET'),
  met = cms.InputTag('caloMet'),
  jets = cms.InputTag('ak4PFJetsCHS'),
  electrons = cms.InputTag('gedGsfElectrons'),
  muons = cms.InputTag('muons'),
  vertices = cms.InputTag('offlinePrimaryVertices'),
  trigSummary = cms.InputTag('hltTriggerSummaryAOD'),
  hltMetFilter = cms.InputTag('hltMET105', '', 'HLT'),
  hltMetCleanFilter = cms.InputTag('hltMETClean65', '', 'HLT'),
  trackLegFilter = cms.InputTag('hltTrk50Filter', '', 'HLT'),
  metSelection = cms.string('pt > 0'),
  jetSelection = cms.string('pt > 0'),
  muonSelection = cms.string('pt > 0'),
  vtxSelection = cms.string('!isFake'),
  njets = cms.uint32(0),
  nmuons = cms.uint32(0),
  leadJetEtaCut = cms.double(2.4),
  requireLeadMatched = cms.bool(True),
  maxMatchDeltaR = cms.double(0.1),
  numGenericTriggerEventPSet = cms.PSet(
    dcsInputTag = cms.InputTag('scalersRawToDigi'),
    dcsPartitions = cms.vint32(),
    andOrDcs = cms.bool(False),
    errorReplyDcs = cms.bool(True),
    dbLabel = cms.string(''),
    andOrHlt = cms.bool(True),
    hltInputTag = cms.InputTag('TriggerResults', '', 'HLT'),
    hltPaths = cms.vstring(),
    hltDBKey = cms.string(''),
    errorReplyHlt = cms.bool(False),
    verbosityLevel = cms.uint32(1)
  ),
  denGenericTriggerEventPSet = cms.PSet(
    dcsInputTag = cms.InputTag('scalersRawToDigi'),
    dcsPartitions = cms.vint32(),
    andOrDcs = cms.bool(False),
    errorReplyDcs = cms.bool(True),
    dbLabel = cms.string(''),
    andOrHlt = cms.bool(True),
    hltInputTag = cms.InputTag('TriggerResults', '', 'HLT'),
    hltPaths = cms.vstring(),
    hltDBKey = cms.string(''),
    errorReplyHlt = cms.bool(False),
    verbosityLevel = cms.uint32(1)
  ),
  histoPSet = cms.PSet(
    metPSet = cms.PSet(),
    phiPSet = cms.PSet(),
    ptPSet = cms.PSet(),
    etaPSet = cms.PSet(),
    metBinning = cms.vdouble(
      0,
      20,
      40,
      60,
      80,
      90,
      100,
      110,
      120,
      130,
      140,
      150,
      160,
      170,
      180,
      190,
      200,
      220,
      240,
      260,
      280,
      300,
      350,
      400,
      450,
      1000
    ),
    ptBinning = cms.vdouble(
      0,
      20,
      40,
      60,
      80,
      90,
      100,
      110,
      120,
      130,
      140,
      150,
      160,
      170,
      180,
      190,
      200,
      220,
      240,
      260,
      280,
      300,
      350,
      400,
      450,
      1000
    ),
    lsPSet = cms.PSet(
      nbins = cms.uint32(2500)
    )
  )
)
