import FWCore.ParameterSet.Config as cms

from .MtdRecoClusterToSimLayerClusterAssociatorByHitsProducer import MtdRecoClusterToSimLayerClusterAssociatorByHitsProducer

mtdRecoClusterToSimLayerClusterAssociatorByHits = MtdRecoClusterToSimLayerClusterAssociatorByHitsProducer()
