import FWCore.ParameterSet.Config as cms

from .MtdRecoClusterToSimLayerClusterAssociatorEDProducer import MtdRecoClusterToSimLayerClusterAssociatorEDProducer

mtdRecoClusterToSimLayerClusterAssociationDefault = MtdRecoClusterToSimLayerClusterAssociatorEDProducer()
