import FWCore.ParameterSet.Config as cms

from .MtdSimLayerClusterToTPAssociatorByTrackIdProducer import MtdSimLayerClusterToTPAssociatorByTrackIdProducer

mtdSimLayerClusterToTPAssociatorByTrackId = MtdSimLayerClusterToTPAssociatorByTrackIdProducer()
