import FWCore.ParameterSet.Config as cms

from .MtdSimLayerClusterToTPAssociatorEDProducer import MtdSimLayerClusterToTPAssociatorEDProducer

mtdSimLayerClusterToTPAssociationDefault = MtdSimLayerClusterToTPAssociatorEDProducer()
