import FWCore.ParameterSet.Config as cms

from .CandidatePointSeededTrackingRegionsEDProducer import CandidatePointSeededTrackingRegionsEDProducer

candidatePointSeededTrackingRegionsFromBeamSpot = CandidatePointSeededTrackingRegionsEDProducer()
