import FWCore.ParameterSet.Config as cms

from .GlobalTrackingRegionFromBeamSpotEDProducer import GlobalTrackingRegionFromBeamSpotEDProducer

globalTrackingRegionFromBeamSpot = GlobalTrackingRegionFromBeamSpotEDProducer()
