import FWCore.ParameterSet.Config as cms

from .GlobalTrackingRegionWithVerticesEDProducer import GlobalTrackingRegionWithVerticesEDProducer

globalTrackingRegionWithVertices = GlobalTrackingRegionWithVerticesEDProducer()
