import FWCore.ParameterSet.Config as cms

from .PixelInactiveAreaTrackingRegionsSeedingLayersProducer import PixelInactiveAreaTrackingRegionsSeedingLayersProducer

pixelInactiveAreaTrackingRegionsAndSeedingLayers = PixelInactiveAreaTrackingRegionsSeedingLayersProducer()
