import FWCore.ParameterSet.Config as cms

from .CandidateSeededTrackingRegionsEDProducer import CandidateSeededTrackingRegionsEDProducer

seededTrackingRegionsFromBeamSpotFixedZLength = CandidateSeededTrackingRegionsEDProducer()
