import FWCore.ParameterSet.Config as cms

from .HITrackingRegionForPrimaryVtxEDProducer import HITrackingRegionForPrimaryVtxEDProducer

hiTrackingRegionFromClusterVtx = HITrackingRegionForPrimaryVtxEDProducer()
