import FWCore.ParameterSet.Config as cms

from .SiStripChannelGainFromDBMiscalibrator import SiStripChannelGainFromDBMiscalibrator

scaleAndSmearSiStripGains = SiStripChannelGainFromDBMiscalibrator()
