import FWCore.ParameterSet.Config as cms

from .PathsAndConsumesOfModulesTestService import PathsAndConsumesOfModulesTestService

PathsAndConsumesOfModulesTestService = PathsAndConsumesOfModulesTestService()
