import FWCore.ParameterSet.Config as cms

testLabel1 = cms.EDProducer('ProducerWithPSetDesc',
  p_int = cms.int32(1),
  noDefaultPset1 = cms.PSet(
    noDefault1 = cms.required.int32,
    noDefault2 = cms.required.vint32,
    noDefault3 = cms.required.uint32,
    noDefault4 = cms.required.vuint32,
    noDefault5 = cms.required.int64,
    noDefault6 = cms.required.vint64,
    noDefault7 = cms.required.uint64,
    noDefault8 = cms.required.vuint64,
    noDefault9 = cms.required.double,
    noDefault10 = cms.required.vdouble,
    noDefault11 = cms.required.bool,
    noDefault12 = cms.required.string,
    noDefault13 = cms.required.vstring,
    noDefault14 = cms.required.EventID,
    noDefault15 = cms.required.VEventID,
    noDefault16 = cms.required.LuminosityBlockID,
    noDefault17 = cms.required.VLuminosityBlockID,
    noDefault18 = cms.required.InputTag,
    noDefault19 = cms.required.VInputTag,
    noDefault20 = cms.required.FileInPath,
    noDefault21 = cms.required.LuminosityBlockRange,
    noDefault22 = cms.required.VLuminosityBlockRange,
    noDefault23 = cms.required.EventRange,
    noDefault24 = cms.required.VEventRange
  ),
  noDefaultPset2 = cms.PSet(
    noDefault1 = cms.required.untracked.int32,
    noDefault2 = cms.required.untracked.vint32,
    noDefault3 = cms.required.untracked.uint32,
    noDefault4 = cms.required.untracked.vuint32,
    noDefault5 = cms.required.untracked.int64,
    noDefault6 = cms.required.untracked.vint64,
    noDefault7 = cms.required.untracked.uint64,
    noDefault8 = cms.required.untracked.vuint64,
    noDefault9 = cms.required.untracked.double,
    noDefault10 = cms.required.untracked.vdouble,
    noDefault11 = cms.required.untracked.bool,
    noDefault12 = cms.required.untracked.string,
    noDefault13 = cms.required.untracked.vstring,
    noDefault14 = cms.required.untracked.EventID,
    noDefault15 = cms.required.untracked.VEventID,
    noDefault16 = cms.required.untracked.LuminosityBlockID,
    noDefault17 = cms.required.untracked.VLuminosityBlockID,
    noDefault18 = cms.required.untracked.InputTag,
    noDefault19 = cms.required.untracked.VInputTag,
    noDefault20 = cms.required.untracked.FileInPath,
    noDefault21 = cms.required.untracked.LuminosityBlockRange,
    noDefault22 = cms.required.untracked.VLuminosityBlockRange,
    noDefault23 = cms.required.untracked.EventRange,
    noDefault24 = cms.required.untracked.VEventRange
  ),
  mightGet = cms.optional.untracked.vstring
)
